### PR TITLE
🌱 bump docker/docker to v26.0.2+incompatible

### PR DESCRIPTION
**Pull request by tuminoid**
Due https://osv.dev/GHSA-x84c-p2g9-rqv9

### CODE REVIEW

**Review by Sunnatillo — APPROVED** [review]
/approve

**Comment by tuminoid** [comment]
/hold

Let's see if our new dependabot branch config finds this and creates PR for it.

**Comment by tuminoid** [comment]
Yes, docker/docker is now v26.0.2 by new dependabot config, this is not needed.

/close

**Pull request closed without merging**
