### PR TITLE
🌱 add KUBECTL_SHA256 passthru

### PR DESCRIPTION
**Pull request by tuminoid**
Pass thru KUBECTL_SHA256 from JJB for upgrade e2e tests.

Manual cherry-pick of #1177 adapted to release-1.3.

### CODE REVIEW

**Comment by tuminoid** [comment]
/test-ubuntu-e2e-feature-release-1-3

This should break, as the fix is commented out.

**Review by Sunnatillo — COMMENTED** [review]
/lgtm

**Review by lentzi90 — COMMENTED** [review]
/approve

**Comment by tuminoid** [comment]
/test-ubuntu-integration-release-1-3 
Flake

**Pull request merged**
