### PR TITLE
🌱 Add lentzi90 as an approver

### PR DESCRIPTION
**Pull request by mboukhalfa**

### CODE REVIEW

**Review by furkatgofurov7 — APPROVED** [review]
Welcome @lentzi90 and thanks for all contributions so far and agreeing to step up as a maintainer!

/approve
/cherry-pick release-1.4
/cherry-pick release-1.3
/cherry-pick release-1.2

**Comment by kashifest** [comment]
/lgtm
Welcome @lentzi90 , thanks a lot for your contributions.

**Pull request merged**
