### PR TITLE
🌱 add KUBECTL_SHA256 passthru

### PR DESCRIPTION
**Pull request by tuminoid**
Pass thru KUBECTL_SHA256 from JJB for upgrade e2e tests.

Manual cherry-pick of #1178 adapted to release-1.5

### CODE REVIEW

**Comment by tuminoid** [comment]
Unrelated test failure.

**Review by Sunnatillo — COMMENTED** [review]
/lgtm

**Review by lentzi90 — COMMENTED** [review]
/approve

**Pull request merged**
