### PR TITLE
🌱 add golang base image check to verify-release.sh

### PR DESCRIPTION
**Pull request by tuminoid**
Verify-release.sh will now check the golang in Dockerfile is the latest of its minor series.

It will be cherry-picked to release branches.

### CODE REVIEW

**Comment by tuminoid** [comment]
/hold
Holding to sync reviews with https://github.com/metal3-io/baremetal-operator/pull/1614 and https://github.com/metal3-io/ip-address-manager/pull/450

**Comment by tuminoid** [comment]
/override test-centos-e2e-integration-main  test-ubuntu-integration-main

**Review by smoshiur1237 — COMMENTED** [review]
/lgtm

**Review by Sunnatillo — APPROVED** [review]
LGTM

**Pull request merged**
