### PR TITLE
🌱 add KUBECTL_SHA256 export for upgrade tests

### PR DESCRIPTION
**Pull request by tuminoid**
Pass thru KUBECTL_SHA256 from JJB for upgrade e2e tests.

### CODE REVIEW

**Comment by tuminoid** [comment]
/hold
WIP

**Comment by tuminoid** [comment]
/cc @lentzi90 @kashifest @mboukhalfa 

Need actual review on this: is this enough, or does it need to be inserted in 'vars.sh` or something so it goes right via Ansible etc.

**Review by Sunnatillo — APPROVED** [review]
/lgtm

**Comment by tuminoid** [comment]
> /cc @lentzi90 @kashifest @mboukhalfa
> 
> Need actual review on this: is this enough, or does it need to be inserted in 'vars.sh` or something so it goes right via Ansible etc.

/hold
for above

**Review by lentzi90 — COMMENTED** [review]
I would say this is enough. Here is my reasoning:

1. For e2e tests, we start in this repo by running the `scripts/ci-e2e.sh` script.
2. The script sources the `environment.sh`
3. We clone metal3-dev-env and run make

Thus, the variables we set in `environment.sh` will propagate to dev-env directly and override any config there that accepts env vars.

/approve

**Comment by Sunnatillo** [comment]
In my opinion, this is enough since you already made the changes on dev-env to make sha overridiable and dev env pick up env variable from capm3. So we should be good

**Comment by mboukhalfa** [comment]
> I would say this is enough. Here is my reasoning:
> 
>     1. For e2e tests, we start in this repo by running the `scripts/ci-e2e.sh` script.
> 
>     2. The script sources the `environment.sh`
> 
>     3. We clone metal3-dev-env and run make
> 
> 
> Thus, the variables we set in `environment.sh` will propagate to dev-env directly and override any config there that accepts env vars.
> 
> /approve

I do not think vars exported from environment.sh will be seen by devenv scripts because make run them in a separate shell so it should be in https://github.com/metal3-io/cluster-api-provider-metal3/blob/890cff97f49e62985f66a66fbd52b13867a0eaf3/scripts/ci-e2e.sh#L37

**Comment by lentzi90** [comment]
> > I would say this is enough. Here is my reasoning:
> > ```
> > 1. For e2e tests, we start in this repo by running the `scripts/ci-e2e.sh` script.
> > 
> > 2. The script sources the `environment.sh`
> > 
> > 3. We clone metal3-dev-env and run make
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Thus, the variables we set in `environment.sh` will propagate to dev-env directly and override any config there that accepts env vars.
> > /approve
> 
> I do not think vars exported from environment.sh will be seen by devenv scripts because make run them in a separate shell so it should be in
> 
> https://github.com/metal3-io/cluster-api-provider-metal3/blob/890cff97f49e62985f66a66fbd52b13867a0eaf3/scripts/ci-e2e.sh#L37

Oh! I always forget Make does that :disappointed: I think you are right and we need to put it in the ci-e2e.sh config section.

**Comment by tuminoid** [comment]
> Oh! I always forget Make does that 😞 I think you are right and we need to put it in the ci-e2e.sh config section.

Thank for the input. I think we need it in `environment.sh` so it is defined in same place as `KUBERNETES_VERSION` as well as in `ci-e2e.sh` which sources `environment.sh`, and in `ci-e2e.sh` we put it in `config_<user>.sh` same as `KUBERNETES_VERSION`. This way they are defined as a pair and they're passthru as a pair.

I've now got WIP version, with bogus sha, which will fail in digest check, if the passthru works as expected.

/test-centos-e2e-integration-main
/test-ubuntu-integration-main

**Comment by tuminoid** [comment]
Wakey wakey Jenkins

/test-centos-e2e-integration-main
/test-ubuntu-integration-main

**Comment by tuminoid** [comment]
This PR is dead to Jenkins apparently. I'll recreate.

/close

**Pull request closed without merging**
