### PR TITLE
🐛 uplift x/net to 0.4.0

### PR DESCRIPTION
**Pull request by tuminoid**
x/net has vulnerabilities GO-2022-1144, GO-2022-0969. Uplift x/net to 0.4.0.

edit: x/text 0.4.0 is not vulnerable, edited description. It will still be uplifted to 0.5.0 due x/net requirements.

### CODE REVIEW

**Review by kashifest — APPROVED** [review]

**Review by furkatgofurov7 — COMMENTED** [review]
Let's cherry-pick these changes down the chain to all release branches which are affected.

/lgtm

**Pull request merged**
