### PR TITLE
🌱 bump CAPI to v1.7.1

### PR DESCRIPTION
**Pull request by kashifest**
as title says

### CODE REVIEW

**Comment by tuminoid** [comment]
We have two now: https://github.com/metal3-io/cluster-api-provider-metal3/pull/1619
which one goes?

**Review by Sunnatillo — COMMENTED** [review]
/lgtm

**Comment by tuminoid** [comment]
/retitle 🌱 bump CAPI to v1.7.1
for prow

**Review by smoshiur1237 — APPROVED** [review]
LGTM

**Pull request merged**
