### PR TITLE
🐛 Remove m3m ownerRef from bmh

### PR DESCRIPTION
**Pull request by shibaPuppy**
**What this PR does / why we need it**:
don't control bmh power state if it goes to provisioned state
provisioned was completed, we should be able to power off the node on a case-by-case. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by furkatgofurov7** [comment]
> provisioned was completed, we should be able to power off the node on a case-by-case.

Thanks for the PR @shibaPuppy. Maybe I missing the use case here, but regardless of the host state, we should not power down the node. Can you elaborate more on your use-case?

**Comment by shibaPuppy** [comment]
> > provisioned was completed, we should be able to power off the node on a case-by-case.
> 
> Thanks for the PR @shibaPuppy. Maybe I missing the use case here, but regardless of the host state, we should not power down the node. Can you elaborate more on your use-case?

@furkatgofurov7 
We are using libvirt node with CAPM3.

I think it should be possible to force power off the vm to proceed with the evacuation due to memory issues.

Similarly, I thought that the PM HW issue should be able to be forcibly turned off.

**Comment by furkatgofurov7** [comment]
> I think it should be possible to force power off the vm to proceed with the evacuation due to memory issues.

that could be taken care by features, like [remediation](https://cluster-api.sigs.k8s.io/tasks/automated-machine-management/healthchecking.html) IMO and not forcing the controller to power down the node

**Comment by shibaPuppy** [comment]
> that could be taken care by features, like [remediation](https://cluster-api.sigs.k8s.io/tasks/automated-machine-management/healthchecking.html) IMO rather than forcing the controller to power down the node

In some cases, after turning off the power, the node where the OS is installed is moved to an isolated rack for inspection.

I haven't used machine-health-check yet.
the kubelet may have issues, but the libvirt vm may not.
may not be able to proceed with reinstalling the OS.

**Comment by Rozzii** [comment]
As far as I can see there were no decision on this PR and @shibaPuppy is still active so I have reopened this.
/cc @dtantsur @kashifest @zaneb @elfosardo @hroyrh @hardys    let's expand the scope of reviewers a a bit.

**Comment by zaneb** [comment]
I agree that we should not be continuously forcing the power control to be on, which it appears we are currently doing because `setHostSpec()` is called from `Update()`. We just need to make sure it is on at the time the host is provisioned.

I think I'd prefer to set it inside the same block that we are setting the image, rather than relying on the state, since that could be racy. But in practice I expect this is probably ok.

/cc @honza

**Comment by shibaPuppy** [comment]
@honza @zaneb @Rozzii 
really want this feature :sob:

**Review by Rozzii — APPROVED** [review]
/lgtm

**Comment by kashifest** [comment]
> I think I'd prefer to set it inside the same block that we are setting the image, rather than relying on the state, since that could be racy. But in practice I expect this is probably ok.
> 
> /cc @honza

This also makes sense to me. @honza opinions?

**Comment by zaneb** [comment]
Looking into this a bit more deeply...

I looked at [our fork of the original CAPBM](https://github.com/openshift/cluster-api-provider-baremetal/blob/master/pkg/cloud/baremetal/actuators/machine/actuator.go) (from the pre-CAPM3 times), and the `provisionHost()` function (equivalent of `setHostSpec()` here) also [sets `Online` to `true` unconditionally](https://github.com/openshift/cluster-api-provider-baremetal/blob/master/pkg/cloud/baremetal/actuators/machine/actuator.go#L590). That's OK though, because it is only called from `Create()`, so it only happens when the Machine is in the `Provisioning` phase.

What really changed in CAPM3 is that 31d394f1ab4323c74d11ccbe559dc46d6287533e started calling `setHostSpec()` not only from `Associate()` but also from `Update()`. Presumably this means it now gets called all the time no matter what phase the Machine is in. Since the purpose of this patch was to set the owner reference on the BMH, which we've already agreed (in #1358) is wrong, maybe we should revert that whole patch.

**Comment by Rozzii** [comment]
/hold
I am holding this based on @zaneb 's reply https://github.com/metal3-io/cluster-api-provider-metal3/pull/1008#issuecomment-1891113489 , could we discuss this @shibaPuppy ?

**Comment by shibaPuppy** [comment]
@Rozzii @zaneb 
I am not sure about my opinion as I lack a deep understanding of the CAPM3.

I think the `power on` function of baremetal nodes through a call to `provisionHost()` is essential, but I don't think there is a need to force the state in metal3machine when it is in `provisioned` state.

**Comment by shibaPuppy** [comment]
> I think I'd prefer to set it inside the same block that we are setting the image, rather than relying on the state, since that could be racy. But in practice I expect this is probably ok.

Does the image block match that line?

https://github.com/metal3-io/cluster-api-provider-metal3/pull/1008/files#diff-cd2cdab0bdcc6b6e359db724b479ca86f879705fbfbcdddba7dbc876941e89bbR1121-L1151

@kashifest @zaneb @Rozzii

**Comment by zaneb** [comment]
> @Rozzii @zaneb I am not sure about my opinion as I lack a deep understanding of the CAPM3.
> 
> I think the `power on` function of baremetal nodes through a call to `provisionHost()` is essential, but I don't think there is a need to force the state in metal3machine when it is in `provisioned` state.

Yes, correct. It should do it once and leave it.

I think we should stop calling `setHostSpec()` from `Update()`, which would have the same effect by reducing complexity instead of adding to it.

We should also stop setting the owner reference, because we agreed in #1358 that that's a bug.

A straight revert of https://github.com/metal3-io/cluster-api-provider-metal3/commit/31d394f1ab4323c74d11ccbe559dc46d6287533e would achieve both.

**Comment by shibaPuppy** [comment]
/retitle 🐛 Remove m3m ownerRef from bmh

**Comment by shibaPuppy** [comment]
@Rozzii @zaneb 
[owerRef commit](https://github.com/metal3-io/cluster-api-provider-metal3/commit/31d394f1ab4323c74d11ccbe559dc46d6287533e) was not reverted, so I wrote a commit to remove it.

**Comment by dtantsur** [comment]
Do we need to keep `DeleteOwnerRef` for the time being? I'm thinking of an upgrade scenario where someone already has hosts with OwnerReferences that now are going to stick forever.

**Comment by kashifest** [comment]
We agreed to close this in favor of https://github.com/metal3-io/cluster-api-provider-metal3/pull/1742#issuecomment-2160751565 since this PR was opened initially with different purpose and removing ownerreference is dealt on the other one

**Pull request closed without merging**
