### PR TITLE
✨ Uplift BMO modules to latest (March 2022)

### PR DESCRIPTION
**Pull request by kashifest**
Fixes # Also fixing the modules path in hack/tools/go.mod

### CODE REVIEW

**Review by Rozzii — APPROVED** [review]
LGTM

**Review by smoshiur1237 — APPROVED** [review]
/lgtm

**Review by fmuyassarov — APPROVED** [review]

**Comment by fmuyassarov** [comment]
/retitle 🌱 Uplift BMO modules to latest (March 2022)

**Pull request merged**
