### PR TITLE
🌱 Bump CAPI to v1.6.2

### PR DESCRIPTION
**Pull request by adilGhaffarDev**
as title says
This PR also uses `k8s.io/utils/ptr` instead of `k8s.io/utils/pointer`

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
/approve

**Comment by kashifest** [comment]
> @kashifest: #1467 failed to apply on top of branch "release-1.6":
> 

@adilGhaffarDev we need a manual cherry pick

**Comment by adilGhaffarDev** [comment]
> @adilGhaffarDev we need a manual cherry pick

Yes, I thought so. I will do it

**Pull request merged**
