### PR TITLE
:seedling: Add Centos 9 support for release-0.5 branch e2e test

### PR DESCRIPTION
**Pull request by Rozzii**
Add Centos 9 support to v0.5 e2e tests,

### CODE REVIEW

**Comment by Rozzii** [comment]
test-v0a5-centos-e2e

**Comment by Rozzii** [comment]
test-v1a5-centos-e2e

**Review by furkatgofurov7 — CHANGES_REQUESTED** [review]
This https://github.com/metal3-io/cluster-api-provider-metal3/blob/release-0.5/test/e2e/node_reuse_test.go#L82 also needs to be updated

**Comment by Rozzii** [comment]
> This https://github.com/metal3-io/cluster-api-provider-metal3/blob/release-0.5/test/e2e/node_reuse_test.go#L82 also needs to be updated

Thanks, done.

**Review by furkatgofurov7 — APPROVED** [review]
/approve

**Comment by furkatgofurov7** [comment]
/retitle :seedling: Add Centos 9 support for release-0.5 branch e2e test

**Pull request merged**
