### PR TITLE
🌱 Backport e2e log improvements to release-1.3

### PR DESCRIPTION
**Pull request by lentzi90**
**What this PR does / why we need it**:

This is a manual backport of #922 and #924.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by Sunnatillo** [comment]
LGTM

**Review by kashifest — COMMENTED** [review]
/lgtm

**Pull request merged**
