### PR TITLE
🌱 Configure dependabot for release-1.6 branch

### PR DESCRIPTION
**Pull request by kashifest**
This PR adds release-1.6 branch config in dependabot.
Signed-off-by: Kashif Khan <kashif.khan@est.tech>

### CODE REVIEW

**Review by tuminoid — COMMENTED** [review]
/approve

**Comment by tuminoid** [comment]
/override metal3-ubuntu-e2e-integration-test-main metal3-centos-e2e-integration-test-main

**Comment by tuminoid** [comment]
PR storm incoming in 3, 2, 1, ... :smile:

**Review by Rozzii — COMMENTED** [review]
/lgtm

**Review by Rozzii — COMMENTED** [review]
/lgtm

**Pull request merged**
