### PR TITLE
🌱  Bump dependencies in hack/tools to match CAPI 1.2 release branch

### PR DESCRIPTION
**Pull request by kashifest**

### CODE REVIEW

**Review by furkatgofurov7 — APPROVED** [review]
The title should state maybe: *downgrade*? 

/cc @mboukhalfa @lentzi90

**Review by lentzi90 — COMMENTED** [review]
/lgtm
But I agree with @furkatgofurov7 that it would be good to mention in the title that it is a downgrade. Normally "bump" would be for a newer version.

**Pull request merged**
