### PR TITLE
 🌱 Bump CAPI to v1.3.1

### PR DESCRIPTION
**Pull request by kashifest**

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Review by furkatgofurov7 — APPROVED** [review]
/hold
to clarify tests results from e2e run in https://github.com/metal3-io/cluster-api-provider-metal3/pull/815#issuecomment-1359265477

**Comment by furkatgofurov7** [comment]
> to clarify tests results from e2e run in [#815 (comment)](https://github.com/metal3-io/cluster-api-provider-metal3/pull/815#issuecomment-1359265477)

should be all good (https://jenkins.nordix.org/view/Metal3/job/metal3_capm3_release-1-3_e2e_test_ubuntu/1/)
/hold cancel

**Pull request merged**
