### PR TITLE
:seedling: Fix code quality issues in TLS configuration code

### PR DESCRIPTION
**Pull request by as20203**
Fixed the code quality issues mentioned in [1320](https://github.com/metal3-io/baremetal-operator/issues/1320)

### CODE REVIEW

**Comment by as20203** [comment]
@tuminoid please review. These are the code quality changes for CAPM3 like we did for BMO.

**Comment by tuminoid** [comment]
/retitle :seedling: Fix code quality issues in TLS configuration code

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Review by Sunnatillo — APPROVED** [review]
LGTM

**Review by furkatgofurov7 — APPROVED** [review]

**Pull request merged**
