### PR TITLE
🌱 Update owners file to move inactive approvers/reviewers to emeritus and add Lennart as a reviewer

### PR DESCRIPTION
**Pull request by kashifest**
This PR updates the OWNERS file to move inactive approvers/reviewers to emeritus. Also add Lennart Jern as a reviewer as he has reached the number of commits to be eligible for reviewer.

### CODE REVIEW

**Review by furkatgofurov7 — APPROVED** [review]
/approve

/cc @mboukhalfa @adilGhaffarDev

**Comment by mboukhalfa** [comment]
Great works @lentzi90 
Thanks @Xenwar for you contributions
/lgtm

**Pull request merged**
