### PR TITLE
:seedling: add support for 1.10 in e2e

### PR DESCRIPTION
**Pull request by tuminoid**
Add support for CAPM3 1.10 development in CI.

### CODE REVIEW

**Comment by tuminoid** [comment]
/hold
For 1.9 to be cut, and also clarity on the content.

**Comment by tuminoid** [comment]
> For 1.9 to be cut, and also clarity on the content.

1.9 should be fine as-is (without this PR) contract wise.

Discussed with @kashifest , this seems to be fine regarding 1.10 metadata/contracts etc. Need to sync with @adilGhaffarDev tomorrow, as release-1.8 cut was messy around these.

Holding until final clear and 1.9 is cut.

/cc @kashifest @adilGhaffarDev

**Review by Rozzii — COMMENTED** [review]
/lgtm

**Comment by tuminoid** [comment]
This is expected to fail until 1.9 is out, and even then we need to merge dev-env pr first. https://github.com/metal3-io/metal3-dev-env/pull/1485

**Pull request merged**
