### PR TITLE
🌱 bump k8s.io/* deps to v0.28.13

### PR DESCRIPTION
**Pull request by tuminoid**
Dependabot's PR for this is again full of unrelated mods and even downgrades, so let's do it manually again.

### CODE REVIEW

**Comment by tuminoid** [comment]
This will supersede https://github.com/metal3-io/cluster-api-provider-metal3/pull/1912

**Review by smoshiur1237 — COMMENTED** [review]
/approve

**Review by Sunnatillo — COMMENTED** [review]
/approve

**Review by Sunnatillo — COMMENTED** [review]
/lgtm

**Pull request merged**
