### PR TITLE
🌱 Bump BMO and minor fix in e2e config

### PR DESCRIPTION
**Pull request by adilGhaffarDev**
**What this PR does / why we need it**:
Bumping BMO and minor fix in e2e config

### CODE REVIEW

**Review by kashifest — COMMENTED** [review]
you have to also bump `github.com/metal3-io/baremetal-operator/pkg/hardwareutils` in a couple of the go mods

**Review by Sunnatillo — COMMENTED** [review]
/approve

**Comment by adilGhaffarDev** [comment]
> you have to also bump `github.com/metal3-io/baremetal-operator/pkg/hardwareutils` in a couple of the go mods

done

**Review by kashifest — COMMENTED** [review]
/lgtm

**Pull request merged**
