### PR TITLE
:seedling: Fix some typos

### PR DESCRIPTION
**Pull request by Hellcatlk**
Signed-off-by: Zou Yu <zouy.fnst@cn.fujitsu.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by fmuyassarov — COMMENTED** [review]
/lgtm

**Review by kashifest — APPROVED** [review]

**Pull request merged**
