### PR TITLE
🌱 Uplift CAPI version in e2e tests to 1.1.3 and 0.4.8 and CAPI go modules to 1.1.3

### PR DESCRIPTION
**Pull request by kashifest**

### CODE REVIEW

**Comment by kashifest** [comment]
I am somehow not liking the idea of hardcoding CAPI versions in e2e tests. I will try to pull up a separate PR for fixing this.

**Review by namnx228 — COMMENTED** [review]
/lgtm

**Review by Rozzii — APPROVED** [review]

**Review by furkatgofurov7 — APPROVED** [review]
/retitle 🌱 Uplift CAPI version in e2e tests to 1.1.3 and 0.4.8 and CAPI go modules to 1.1.3
/approve

**Pull request merged**
