### PR TITLE
:book: remove .mdlrc and fix complaints

### PR DESCRIPTION
**Pull request by tuminoid**
Remove .mdlrc to have the same markdownlint rules as all other repos. We have plenty of long lines in shell sections and tables, so we move the MD013 rule ignore to the command line of the script to make it clear.

### CODE REVIEW

**Comment by tuminoid** [comment]
/test all

Testing CI changes.

**Review by Sunnatillo — COMMENTED** [review]
/lgtm

**Review by lentzi90 — COMMENTED** [review]
/approve

**Pull request merged**
