### PR TITLE
🌱 Update ipam config image patch and kustomization

### PR DESCRIPTION
**Pull request by furkatgofurov7**
**What this PR does / why we need it**:
This PR updates the image patch and kustomization for the IPAM controller. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by kashifest — APPROVED** [review]
Nice catch. Wonder of renovate would help us catch these somehow. We always forget these tiny changes.

**Review by namnx228 — APPROVED** [review]
LGTM

**Review by fmuyassarov — COMMENTED** [review]
/lgtm

**Pull request merged**
