### PR TITLE
🌱 Add gosec file and related changes in release-0.5 branch

### PR DESCRIPTION
**Pull request by kashifest**
- [Add gosec file for go security checks](https://github.com/metal3-io/cluster-api-provider-metal3/commit/be2c770f7e7d421298d8c02813701450065b3159)

- [Use crypto/rand instead of math/rand](https://github.com/metal3-io/cluster-api-provider-metal3/commit/7a6747d6c18c58e56b57f374ec76e351d7351f81)
 
- [Reassign loop variable to address gosec G601](https://github.com/metal3-io/cluster-api-provider-metal3/commit/22e3edd51f099e1beb954d0d0d4c79663db5cef2)
 
- [Cleanup bad filepath using filepath.Clean](https://github.com/metal3-io/cluster-api-provider-metal3/commit/31d76469e8660fb3bb023fd39005e923ba1c8db3)
 
- [Fix unsafe defer call to file.Close()](https://github.com/metal3-io/cluster-api-provider-metal3/commit/ab30c48124b1f2ffca4b56275ec43c9b91eb7025)
 
- [Exclude rule G107 and include concurrency](https://github.com/metal3-io/cluster-api-provider-metal3/commit/33e42c5afce453876cd6db6c12d915dd383dfe68)

### CODE REVIEW

**Review by furkatgofurov7 — APPROVED** [review]
/approve

**Comment by kashifest** [comment]
/test-v1a5-ubuntu-e2e
@furkatgofurov7 any idea what cause the failure ?

**Review by fmuyassarov — COMMENTED** [review]
/lgtm

**Pull request merged**
