### PR TITLE
Cleanup downloaded file

### PR DESCRIPTION
**Pull request by MaXinjian**
Signed-off-by: Ma Xinjian <maxj.fnst@cn.fujitsu.com>

**What this PR does / why we need it**:
```
$ make test
$ ls -l /tmp/ | grep kubebuilder-tools
-rw-r--r--  1 root root 52352311 Nov 25 16:33 kubebuilder-tools-1.16.4-linux-amd64.tar.gz
```
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by maelk** [comment]
/ok-to-test
/approve

Could you please add short description to your PR ?

**Comment by maelk** [comment]
@fmuyassarov Metal3-dev-env is broken right now. This needs to be retriggered once the issue is fixed

**Comment by fmuyassarov** [comment]
> @fmuyassarov Metal3-dev-env is broken right now. This needs to be retriggered once the issue is fixed

Sorry for that. I already have a fix [#565](https://github.com/metal3-io/metal3-dev-env/pull/565) 
Will trigger the CI here once 565 is merged.

**Comment by fmuyassarov** [comment]
CI should be fixed now hopefully :) 
/test-integration

**Pull request merged**
