### PR TITLE
:seedling: fix ControlPlaneEndpoint in metal3cluster_manager

### PR DESCRIPTION
**Pull request by zhouhao3**
**What this PR does / why we need it**:

Avoid returning err with nil in error cases

### CODE REVIEW

**Comment by zhouhao3** [comment]
cc @kashifest @furkatgofurov7 @smoshiur1237

**Comment by zhouhao3** [comment]
PTAL

**Comment by Xenwar** [comment]
would it be possible to squash the commits

**Comment by zhouhao3** [comment]
I think these two commits fix two different problems. Should not be squashed.

**Comment by zhouhao3** [comment]
@furkatgofurov7 @smoshiur1237 PTAL

**Comment by zhouhao3** [comment]
@kashifest @furkatgofurov7 @smoshiur1237 PTAL

**Review by furkatgofurov7 — COMMENTED** [review]
Thanks!

/lgtm

**Pull request merged**
