### PR TITLE
🐛 Cleanup code duplication from data manager

### PR DESCRIPTION
**Pull request by furkatgofurov7**
**What this PR does / why we need it**:
As per discussion in [comment](https://github.com/metal3-io/cluster-api-provider-metal3/pull/169#discussion_r624987647).

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by namnx228** [comment]
LGTM

**Review by smoshiur1237 — COMMENTED** [review]
Looks good to me.

**Review by fmuyassarov — COMMENTED** [review]
/lgtm

**Review by kashifest — APPROVED** [review]

**Pull request merged**
