### PR TITLE
🐛 Install ginkgo directly instead of building it using go-modules

### PR DESCRIPTION
**Pull request by kashifest**
Fixes https://github.com/metal3-io/cluster-api-provider-metal3/issues/1413

### CODE REVIEW

**Comment by kashifest** [comment]
/hold
Need to fix the issues

**Review by tuminoid — COMMENTED** [review]
Nice, no more dirty go.mod and it is in line with other tools as well.

/lgtm

**Comment by kashifest** [comment]
cc @lentzi90

**Review by lentzi90 — COMMENTED** [review]
/approve

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Pull request merged**
