### PR TITLE
🌱 Bump dependencies: CAPI to v1.1.6, IPAM to v1.1.4 and BMO to v0.1.1

### PR DESCRIPTION
**Pull request by furkatgofurov7**
**What this PR does / why we need it**:

additionally adds gomod.sh script to pass gomod prow job added in https://github.com/metal3-io/project-infra/commit/ecdce6a7b3ee5f231a77a43897c5f4949119b6ef

IPAM release ref: https://github.com/metal3-io/ip-address-manager/releases/tag/v1.1.4
BMO release ref: https://github.com/metal3-io/baremetal-operator/releases/tag/v0.1.1

### CODE REVIEW

**Review by kashifest — APPROVED** [review]
Please change the title accordingly

**Comment by furkatgofurov7** [comment]
> Please change the title accordingly

Done!

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Pull request merged**
