### PR TITLE
🌱 Add e2e scalability test with fake systems

### PR DESCRIPTION
**Pull request by mboukhalfa**
This PR introduces a scalability end-to-end test for CAPM3, applying multiple clusters using ClusterClass and reusing the existing ScaleSpec test framework from Cluster API (CAPI). The test is designed to simulate a large-scale environment with realistic configurations and is based on both FakeIPA and FKAS for authentication and endpoint management.

Test passed here: https://jenkins.nordix.org/view/Metal3/job/metal3-centos-e2e-scalability-test-main/9/console

### CODE REVIEW

**Comment by mboukhalfa** [comment]
test ?

**Comment by mquhuy** [comment]
@mboukhalfa We've been discussing on how to uncouple capm3 e2e from dev-env. Is it possible to design functions to run/configure fake-ipa in capm3, instead of relying on dev-env?

**Comment by tuminoid** [comment]
/retitle WIP: 🌱 Add scalablity test with fakeIPA
let's make it clear it is not intended to be merged as-is (points to private forks etc)

**Comment by mquhuy** [comment]
Question: Is this test supposed to add FKAS integration later on, or will that be a separate test(s)?

**Comment by mboukhalfa** [comment]
> Question: Is this test supposed to add FKAS integration later on, or will that be a separate test(s)?

This test already use the FKAS

**Comment by mboukhalfa** [comment]
test ?

**Comment by mboukhalfa** [comment]
/hold 
This test is using the basic test as a trigger for test purposes while waiting for the scalability pipeline to be merged. It also currently uses the Nordix branch of the CAPI test suite since there are some changes needed in CAPI to enable reusing the test with legacy templates instead of duplicating it here in CAPM3. Additionally, it is still using the Nordix branch to incorporate FakeIPA and FKAS, pending the merge of the associated PR.

**Comment by mquhuy** [comment]
The test is running here: https://jenkins.nordix.org/job/metal3-ubuntu-e2e-integration-test-main/724/console

**Comment by tuminoid** [comment]
This will need rebase soon due CAPI/k8s bump hitting main. We should merge this anyways after 1.9 is cut?

**Comment by mquhuy** [comment]
> This will need rebase soon due CAPI/k8s bump hitting main. We should merge this anyways after 1.9 is cut?

I would say we can merge it right now. CAPM3 still has https://github.com/metal3-io/cluster-api-provider-metal3/pull/2155 which is blocking 1.9.0

**Comment by mquhuy** [comment]
Test passed here: https://jenkins.nordix.org/view/Metal3/job/metal3-centos-e2e-scalability-test-main/9/console

**Review by Rozzii — COMMENTED** [review]
/lgtm
Let's see what happens.

**Pull request merged**
