### PR TITLE
:seedling: Bump CAPI to v1.9.0-rc.1

### PR DESCRIPTION
**Pull request by peppi-lotta**
**What this PR does / why we need it**: Bump CAPI from v1.9.0-rc.0 to v1.9.0-rc.1

### CODE REVIEW

**Review by tuminoid — COMMENTED** [review]
/approve

**Review by kashifest — COMMENTED** [review]
/lgtm

**Comment by kashifest** [comment]
ow, this now needs rebase @peppi-lotta

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Pull request merged**
