### PR TITLE
🐛 Fix Makefile command chaining

### PR DESCRIPTION
**Pull request by kashifest**
This PR is also adding the useful build-api and build e2e phonies which was added in main branch Makefile a while ago.

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Review by furkatgofurov7 — CHANGES_REQUESTED** [review]
> This PR is also adding the useful build-api and build e2e phonies which was added in main branch Makefile a while ago.

Scripts to run it is missing in this release branch (check this commit: https://github.com/metal3-io/cluster-api-provider-metal3/pull/827/commits/b640d55d7a3027c6b76bc3affd2c05b6b51eacce) and also it is not enabled in prow job: https://github.com/metal3-io/project-infra/blob/main/prow/config/config.yaml#L717
I would suggest to take care of ^,  merge infra PR, come back here and run new build job and then take this in.

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Review by furkatgofurov7 — APPROVED** [review]

**Pull request merged**
