### PR TITLE
🌱 cleanup hack/ formatting

### PR DESCRIPTION
**Pull request by tuminoid**
Cleanup hack/*.sh formatting, mount dir generalization etc. No functional changes.

### CODE REVIEW

**Review by mboukhalfa — APPROVED** [review]
Thanks for the cleanup

**Review by Sunnatillo — COMMENTED** [review]
LGTM

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Comment by tuminoid** [comment]
OK. This was merged via API during tide debug testing, and it appears there is permission issue in Tide token.

**Pull request merged**
