### PR TITLE
:seedling: Configurable go executable

### PR DESCRIPTION
**Pull request by fhaftmann**
This allows to select a specific go version if multiple go versions are installed on a system.

**What this PR does / why we need it**:

The assumption that the `go` executable refers to a go version suitable for compiling is not always valid; with having the `go` executable parametrized it is possible to choose a suitable executable from a set of local go installations.

### CODE REVIEW

**Comment by tuminoid** [comment]
Hi @fhaftmann, thanks for the PR!

`type -P go` gives you path of first executable `go` in your `$PATH`, which is the same binary executed when you run `go`.  Which cases/configurations does this PR hence fix?

**Review by lentzi90 — COMMENTED** [review]
/approve

**Review by tuminoid — COMMENTED** [review]
We have this funny `GO_VERSION` on L23, that doesn't match up anymore if you change the GO version, but OTOH it doesn't react if your default Go is something else either. So not an issue created by this PR.

LGTM, but I'll let @mboukhalfa  or @kashifest take a look and LGTM. Thank you for the contribution!

**Comment by kashifest** [comment]
I am trying to understand the motivation behind this , even go recommends to remove any prior go installation to have a fresh go tree. Multiple versions also means reproducibility and verification is difficult.

**Comment by lentzi90** [comment]
> I am trying to understand the motivation behind this , even go recommends to remove any prior go installation to have a fresh go tree. Multiple versions also means reproducibility and verification is difficult.

I guess you refer to [this](https://go.dev/doc/install)? It is not really concerned about multiple go versions though. That page describes the "main" go installation, and that should only be one. However, it is perfectly fine to install more versions, and you can do it using go itself. Check this: https://go.dev/doc/manage-install

**Comment by kashifest** [comment]
> I guess you refer to [this](https://go.dev/doc/install)? It is not really concerned about multiple go versions though. That page describes the "main" go installation, and that should only be one. However, it is perfectly fine to install more versions, and you can do it using go itself. Check this: https://go.dev/doc/manage-install

Yes and IMO in upstream code we should be only concerned about the main go installation. Users are ofcourse allowed to use multiple go versions locally, but configurable go versions upstream might give wrong signals IMO.

**Comment by lentzi90** [comment]
> Yes and IMO in upstream code we should be only concerned about the main go installation. Users are ofcourse allowed to use multiple go versions locally, but configurable go versions upstream might give wrong signals IMO.

What would the use of multiple go versions be in that case, if the main installation is the only one we accept? I think this is a valid request that helps developers work on CAPM3 while also working on other projects that may have different go version requirements. It could even be useful when working on CAPM3 release branches.
Forcing developers to reinstall go just to be able to backport a change is not helpful.

**Comment by fhaftmann** [comment]
> > Yes and IMO in upstream code we should be only concerned about the main go installation. Users are ofcourse allowed to use multiple go versions locally, but configurable go versions upstream might give wrong signals IMO.
> 
> What would the use of multiple go versions be in that case, if the main installation is the only one we accept? I think this is a valid request that helps developers work on CAPM3 while also working on other projects that may have different go version requirements. It could even be useful when working on CAPM3 release branches. Forcing developers to reinstall go just to be able to backport a change is not helpful.

That is exactly my intention: I want to compile CAPM3 with the go compiler as required by CAPM3 without fiddling much around. The MR is *not* about compiling different parts of CAPM3 with different go versions, but providing a simple way to choose exactly the required one explicitly.

**Comment by kashifest** [comment]
> What would the use of multiple go versions be in that case, if the main installation is the only one we accept? I think this is a valid request that helps developers work on CAPM3 while also working on other projects that may have different go version requirements. It could even be useful when working on CAPM3 release branches. Forcing developers to reinstall go just to be able to backport a change is not helpful.

I have multiple go in my local env for different release branches of CAPM3, I use either the go1.x.x version to call the binaries or use an alias for go. I don't know how CAPM3 is forcing me to reinstall go without having this particular patch. 

I would let other reviewers decide the fate of this patch.

**Comment by lentzi90** [comment]
> I have multiple go in my local env for different release branches of CAPM3, I use either the go1.x.x version to call the binaries or use an alias for go. 

This patch is allowing you to do that in a simpler way. If you want to use `go1.x.x` you would currently need to modify the Makefile, right? With this patch you would just need to set `GO=go1.x.x` and you can call any make commands like normal.

> I don't know how CAPM3 is forcing me to reinstall go without having this particular patch. 

I'm referring to what you said above: "IMO in upstream code we should be only concerned about the main go installation."
This implies that we should not accept the other versions of go that you may have installed, or in other words, you would have me reinstall go if I want a different version, since the "main" version is all we should care about.

**Comment by fhaftmann** [comment]
> > I have multiple go in my local env for different release branches of CAPM3, I use either the go1.x.x version to call the binaries or use an alias for go.
> 
> This patch is allowing you to do that in a simpler way. If you want to use `go1.x.x` you would currently need to modify the Makefile, right? With this patch you would just need to set `GO=go1.x.x` and you can call any make commands like normal.

To be more explicit – with this patch, giving an *arbitrary* local go installation (e.g. simply the one coming with your distribution), you can bootstrap the desired go version simply using

```sh
GOBIN="$(pwd)/bin" go install golang.org/dl/go1.20.8@latest
bin/go1.20.8 download 
```

without any impact on your development system as such and then continue e. g.

```sh
make GO="$(pwd)/bin/go1.20.8" build 
```

As others have pointed out, AFAIU there is no way to accomplish this currently without manipulating you local development system or ad-hoc patching the Makefile.

**Comment by kashifest** [comment]
> This implies that we should not accept the other versions of go that you may have installed, or in other words, you would have me reinstall go if I want a different version, since the "main" version is all we should care about.

 See my next line. " Users are ofcourse allowed to use multiple go versions locally" . 

> This patch is allowing you to do that in a simpler way. If you want to use `go1.x.x` you would currently need to modify the Makefile, right? With this patch you would just need to set `GO=go1.x.x` and you can call any make commands like normal.

Agree

>  I fail to see how this patch would break anything or even change anyone's wortkflow unless they want to change it by using it. Hence I'd be interested to see specific cases where this patch would have negative impact.

I didn't say it would break anything or would have negative impact. I asked about the necessity of it living in upstream code.  

> To be more explicit – with this patch, giving an _arbitrary_ local go installation (e.g. simply the one coming with your distribution), you can bootstrap the desired go version simply using
> 
> ```shell
> GOBIN="$(pwd)/bin" go install golang.org/dl/go1.20.8@latest
> bin/go1.20.8 download 
> ```
 
> without any impact on your development system as such and then continue e. g.
> 
> ```shell
> make GO="$(pwd)/bin/go1.20.8" build 
> ```
> As others have pointed out, AFAIU there is no way to accomplish this currently without manipulating you local development system or ad-hoc patching the Makefile.

Thanks. I can agree to this that it would make life simpler. 

/lgtm

**Comment by fhaftmann** [comment]
Despite lgtm this is still on hold. Are there any objections to withdraw hold?

**Comment by lentzi90** [comment]
Seems like we have reached consensus.
/hold cancel

**Pull request merged**
