### PR TITLE
🐛 Downgrade ubuntu to 20.04 in e2e tests to fix ironic/bmo communication

### PR DESCRIPTION
**Pull request by mboukhalfa**
This PR downgrade in v1a5 e2e tests after downgrading in the main because of the ironic/bmo communication issue in the new ubuntu 22.04 #635

### CODE REVIEW

**Review by smoshiur1237 — COMMENTED** [review]
/lgtm

**Review by furkatgofurov7 — APPROVED** [review]
/approve
/retitle 🐛 Downgrade ubuntu to 20.04 in e2e tests to fix ironic/bmo communication

**Pull request merged**
