### PR TITLE
🌱 Add envsubst and gomock to hack/tools/go.mod

### PR DESCRIPTION
**Pull request by wgslr**
**What this PR does / why we need it**:
Fixes Makefile targets for building tool binaries, broken by a 'go mod tidy' run [in a recent PR](https://github.com/metal3-io/cluster-api-provider-metal3/pull/206/files#diff-f389ca9ba468c8313b9d514e887e4b8899886bb2d6790352386aaf01da3aa588).

### CODE REVIEW

**Review by kashifest — APPROVED** [review]
please take care of the failed `generate` test

**Review by furkatgofurov7 — COMMENTED** [review]
/lgtm

**Pull request merged**
