### PR TITLE
🌱 Bump golang to v1.22

### LINKED ISSUE #1828: Bump CAPM3 1.7 release branch to Golang 1.22
Release branch release-1.7 has Golang 1.21.x in use. Golang 1.21 support ends in August 2024, when Golang 1.23 is released.

CAPM3 1.7 is in support for quite a while still, so we need to bump it to Go 1.22 before next patch release.

### LINKED ISSUE #1829: Bump CAPM3 1.6 release branch to Golang 1.22
Release branch release-1.6 has Golang 1.21.x in use. Golang 1.21 support ends in August 2024, when Golang 1.23 is released.

CAPM3 1.6 is in support for some time still, so we need to bump it to Go 1.22 before next patch release.

### PR DESCRIPTION
**Pull request by NymanRobin**
This bump is done since golang version v1.21 will be deprecated in August.

Fixes #1828

### CODE REVIEW

**Comment by NymanRobin** [comment]
Seems like a Prow config update is needed first! The PR for prow config update can be found here: https://github.com/metal3-io/project-infra/pull/821

@smoshiur1237 do I remember correctly that the configuration has still to be applied manually after the PR merges on project-infra side?

**Comment by smoshiur1237** [comment]
> Seems like a Prow config update is needed first! The PR for prow config update can be found here: [metal3-io/project-infra#821](https://github.com/metal3-io/project-infra/pull/821)
> 
> @smoshiur1237 do I remember correctly that the configuration has still to be applied manually after the PR merges on project-infra side?

I think after we have changed the config in project-infra, we need to apply it manually in PROW.

**Review by smoshiur1237 — COMMENTED** [review]
/approve

**Pull request merged**
