### PR TITLE
🌱 Update golang to latest to match version across all repos

### PR DESCRIPTION
**Pull request by furkatgofurov7**
**What this PR does / why we need it**:
In order to avoid differences in go version across all repositories, this PR updates go to the latest in hack scripts.

### CODE REVIEW

**Comment by furkatgofurov7** [comment]
@maelk I will open the same type of PR in IPAM, BMO and HCC repos. The motivation behind this is from [project-infra/pull/124](https://github.com/metal3-io/project-infra/pull/124), but that one also needs to be updated from 1.14.4 to 1.15.3

**Comment by fmuyassarov** [comment]
There is also [Titlfile](https://github.com/metal3-io/cluster-api-provider-metal3/blob/455897de994f66935ca18eb7bc25d51f75758f8c/Tiltfile#L201) that is using 1.13.15.

**Comment by furkatgofurov7** [comment]
> There is also [Titlfile](https://github.com/metal3-io/cluster-api-provider-metal3/blob/455897de994f66935ca18eb7bc25d51f75758f8c/Tiltfile#L201) that is using 1.13.15.

Thanks, updated.

**Pull request merged**
