### PR TITLE
✨ Add ChecksumType field in image

### PR DESCRIPTION
**Pull request by maelk**
**What this PR does / why we need it**:
This PR adds support for the new BMH field ChecksumType in the image, and updates all the dependencies.

### CODE REVIEW

**Comment by furkatgofurov7** [comment]
@maelk, is md5 a default `ChecksumType` in CAPM3? are sha256, sha512 can be used as well?

**Comment by maelk** [comment]
yes, metal3-dev-env uses md5sum to compute the checksum. Other are also supported.

**Comment by furkatgofurov7** [comment]
Looks good to me. But someone who has more expertise in repo shall review.

**Pull request merged**
