### PR TITLE
🌱 bump BMO to 0.3.0

### PR DESCRIPTION
**Pull request by tuminoid**
Bump BMO and hardwareutils to 0.3.0

### CODE REVIEW

**Comment by tuminoid** [comment]
/test-ubuntu-e2e-feature-main
Work, Github, work :pray:

**Comment by tuminoid** [comment]
/test-ubuntu-integration-main  
/test-centos-e2e-integration-main 
//test-ubuntu-e2e-feature-main

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Review by kashifest — APPROVED** [review]

**Pull request merged**
