### PR TITLE
⚠️ Uplift CAPI to prerelease v1.1.0-beta.1

### PR DESCRIPTION
**Pull request by furkatgofurov7**
**What this PR does / why we need it**:
Uplifts:
- capi  v1.1.0-beta.1
- sigs.k8s.io/cluster-api/test v1.1.0-beta.1
- controller tools v0.7.1-0.20211110210727-ab52f76cc7d1

### CODE REVIEW

**Review by kashifest — APPROVED** [review]

**Comment by furkatgofurov7** [comment]
I will break this down into two (this is tackling uplifting to prerelease and e2e issues in the same patch, latter will come in a follow up) and remove for testing purposes commit.

**Pull request merged**
