### PR TITLE
🌱 Change dev-env default branch from master to main in e2e script

### PR DESCRIPTION
**Pull request by mboukhalfa**
metal3 Dev-env default branch was changed to main this PR updates CAPM3 accordingly

### CODE REVIEW

**Review by lentzi90 — APPROVED** [review]

**Review by kashifest — APPROVED** [review]

**Review by namnx228 — COMMENTED** [review]
/lgtm

**Review by furkatgofurov7 — APPROVED** [review]
/retitle 🌱 Change dev-env default branch from master to main in e2e script

**Pull request merged**
