### PR TITLE
🌱Cover upgrade test requirements in node reuse e2e tests

### PR DESCRIPTION
**Pull request by mboukhalfa**
This PR adds image and binary upgrade onto node_reuse test

### CODE REVIEW

**Review by namnx228 — COMMENTED** [review]
/lgtm

**Comment by fmuyassarov** [comment]
/retitle 🌱 Cover upgrade test requirements in node_reuse test

**Comment by furkatgofurov7** [comment]
@mboukhalfa this needs a rebase. Thanks for your patience!

**Comment by furkatgofurov7** [comment]
Strange, this is passing locally
/retest

**Review by namnx228 — COMMENTED** [review]
/lgtm

**Review by furkatgofurov7 — APPROVED** [review]
/retitle 🌱Cover upgrade test requirements in node reuse e2e tests
/approve

**Review by namnx228 — COMMENTED** [review]
/lgtm

**Pull request merged**
