### PR TITLE
:bug: Fixing bmo and ironic version for clusterctl tests

### LINKED ISSUE #1832: clusterctl tests are failing
### Which jobs are failing?

 metal3-periodic-e2e-clusterctl-upgrade

### Which tests are failing?

- metal3-periodic-e2e-clusterctl-upgrade-test-main (https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3-periodic-e2e-clusterctl-upgrade-test-main/)
- metal3-periodic-e2e-clusterctl-upgrade-test-release-1-5 (https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3-periodic-e2e-clusterctl-upgrade-test-release-1-5/)
- metal3-periodic-e2e-clusterctl-upgrade-test-release-1-6 (https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3-periodic-e2e-clusterctl-upgrade-test-release-1-6/)
- metal3-periodic-e2e-clusterctl-upgrade-test-release-1-7 (https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3-periodic-e2e-clusterctl-upgrade-test-release-1-7/)

### Since when has it been failing?

They started failing when we modified upgrade tests. Previously there was only the following tests:
- 1.5 -> main
- 1.6 -> main 
- 1.7 -> main etc, 
and they were all running on the main branch.

Now we have upgrade for each supported branch:

-  Main Branch: 1.6 -> main, 1.7 -> main
-  1.7 Branch: 1.6 -> 1.7, 1.5 -> 1.7
-  1.6 Branch: 1.5 -> 1.6

### Jenkins link

https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3-periodic-e2e-clusterctl-upgrade-test-main/

### Reason for failure (if possible)

After adding the above tests we start seeing issues with the ironic and bmo versions. Due to which tests started failing

### Anything else we need to know?

_No response_

### Label(s) to be applied

/kind failing-test
One or more /area label. See https://github.com/metal3-io/cluster-api-provider-metal3/labels for the list of labels.

### PR DESCRIPTION
**Pull request by adilGhaffarDev**
**What this PR does / why we need it**:
Manual backport of this PR: https://github.com/metal3-io/cluster-api-provider-metal3/pull/1596 on 1.6 branch.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1832

### CODE REVIEW

**Review by smoshiur1237 — COMMENTED** [review]
/approve

**Comment by adilGhaffarDev** [comment]
@mboukhalfa, please check

**Pull request merged**
