### PR TITLE
🌱 Use same version of Calico images as in metal3-dev-env

### PR DESCRIPTION
**Pull request by fmuyassarov**
**What this PR does / why we need it**:
Since the latest calico images version is v3.20.0, we are pre-pulling them into the vanilla images to avoid Docker Hub pull rate limit issue. However, e2e is using v3.19.1 images, causing to pull images from docker.

### CODE REVIEW

**Comment by fmuyassarov** [comment]
We need to find a way that keep calico images version in sync with what we ship inside the node images.

**Comment by furkatgofurov7** [comment]
> We need to find a way that keep calico images version in sync with what we ship inside the node images.

configure renovate for CAPM3 repo?

**Review by kashifest — APPROVED** [review]

**Pull request closed without merging**
