### PR TITLE
:book: update README.md

### PR DESCRIPTION
**Pull request by tuminoid**
Update build badge URLs, and update/remove non-1.5 related information related to testing etc.

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
/approve

**Comment by tuminoid** [comment]
> /approve cancel
> 
> Looks like the badges still has 1.4 in them

Fixed, good catch.

**Review by lentzi90 — COMMENTED** [review]
/approve

**Review by Sunnatillo — APPROVED** [review]
/lgtm

**Pull request merged**
