### PR TITLE
✨  Add live-iso support to CAPI Metal3 provider

### PR DESCRIPTION
**Pull request by levsha**
https://github.com/metal3-io/baremetal-operator/pull/759 adds "live-iso" image format support to BMO.
However CAPI needs to support it too for full functionality is image-related fields usually come from Metal3MachineTemplate trough Metal3Machine to BareMetalHost.

Tested: on a local kind cluster.

### CODE REVIEW

**Comment by fmuyassarov** [comment]
@levsha you are probably missing `make generate` changes. Can you please run make generate and add the changes?

**Comment by levsha** [comment]
> @levsha you are probably missing `make generate` changes. Can you please run make generate and add the changes?

That helped. Thanks!

**Comment by maelk** [comment]
lgtm

**Comment by kashifest** [comment]
Do we need to add this to CAPM3 v1a3 types as well? Can't we live with v1a4 only now since v1a3 is close to its lifetime ?

**Comment by levsha** [comment]
> Do we need to add this to CAPM3 v1a3 types as well? Can't we live with v1a4 only now since v1a3 is close to its lifetime ?

I guess it should be ok to only have it in v1a4 only. Especially that this is new functionality, so we don't have to backport it.

**Comment by levsha** [comment]
> Do we need to add this to CAPM3 v1a3 types as well? Can't we live with v1a4 only now since v1a3 is close to its lifetime ?

I've rolled back changes for v1alpha3

**Review by kashifest — APPROVED** [review]

**Review by furkatgofurov7 — COMMENTED** [review]
/lgtm

**Pull request merged**
