### PR TITLE
📖 Add Sunnat as a reviewer

### PR DESCRIPTION
**Pull request by furkatgofurov7**
**What this PR does / why we need it**:
Adding @Sunnatillo to the reviewers list since he has [10 commits](https://github.com/metal3-io/cluster-api-provider-metal3/commits?author=Sunnatillo) in the repo and helps with reviews consistently.

### CODE REVIEW

**Comment by tuminoid** [comment]
/cherry-pick release-1.3

Cherry picks need to be one per comment.

**Comment by tuminoid** [comment]
/cherry-pick release-1.2

Cherry picks need to be one per comment.

**Comment by furkatgofurov7** [comment]
> Cherry picks need to be one per comment.

@tuminoid I do not think that is the case by looking at https://github.com/metal3-io/cluster-api-provider-metal3/pull/943#issuecomment-1525516230

**Comment by mboukhalfa** [comment]
Great work @Sunnatillo 
/approve

**Comment by tuminoid** [comment]
> > Cherry picks need to be one per comment.
> 
> @tuminoid I do not think that is the case by looking at [#943 (comment)](https://github.com/metal3-io/cluster-api-provider-metal3/pull/943#issuecomment-1525516230)

Well there are dozen of others where it has only reacted to the first cherry pick. Let this be then a test then which way it works. It could be the behavior was fixed by the recent prow uplifts?

**Comment by kashifest** [comment]
/lgtm

Great work @Sunnatillo

**Comment by furkatgofurov7** [comment]
> Let this be then a test then which way it works

it worked

**Comment by tuminoid** [comment]
> > Let this be then a test then which way it works
> 
> it worked

Good, its been pretty annoying when it hasn't :+1:

**Pull request merged**
