### PR TITLE
🌱 Add v1.2 CAPI release contract to e2e metadata file

### PR DESCRIPTION
**Pull request by furkatgofurov7**
**What this PR does / why we need it**:
Also, fetch correct CAPI release when running e2e upgrade tests `{GINKGO_FOCUS:-} == "upgrade"`

This is a follow-up to #674

### CODE REVIEW

**Comment by furkatgofurov7** [comment]
/hold
Needs https://github.com/metal3-io/metal3-dev-env/pull/1050 to test these changes properly. 
/cc @adilGhaffarDev

**Comment by furkatgofurov7** [comment]
`clusterctl upgrade apply --contract v1beta1` fails the e2e upgrade test and the reason being is, we are using pre-release of the CAPM3 provider (release candidate) and for that clusterctl expects to specify the versions instead of providing the contract. We have faced the same issue in ansible upgrade tests earlier, xref comment: https://github.com/metal3-io/metal3-dev-env/pull/1050#discussion_r949152661
I see two options: 

1. either rework/hack https://github.com/metal3-io/cluster-api-provider-metal3/blob/55a11c20eafd312eeaca3455fc239751adfb697d/test/e2e/upgrade_management_cluster_test.go#L278-L283 `UpgradeManagementClusterAndWait` func from CAPI to pass the specific versions of all providers (capi, bootstrap, kcp and capm3) 
2. or drop a proper release of capm3 (i.e v1.2.0) and then update the e2e metadata files as in this PR

Any thoughts or other suggestions?

/cc @kashifest  @lentzi90 @mboukhalfa

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Comment by lentzi90** [comment]
I wonder... is the upgrade test failing because this PR isn't merged yet or is there something wrong with the tag/release?
> failed to find releases tagged with a valid semantic version number

**Comment by kashifest** [comment]
Testing this PR towards release-1.2
/test-upgrade-e2e-main

**Pull request merged**
