### PR TITLE
Report config error

### LINKED ISSUE #682: failed to update BaremetalHost: host not found for machine
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

Metal3Machine failed to update BareMetalHost, and there's no other log between Associate and Update as follow. It seems Associate return at https://github.com/metal3-io/cluster-api-provider-metal3/blob/main/baremetal/metal3machine_manager.go#L297 , and can not recovered.

```
I0811 07:15:49.786114       1 metal3machine_manager.go:294] controllers/Metal3Machine/Metal3Machine-controller "msg"="Associating machine" "cluster"="dpu-cluster" "metal3-cluster"="dpu-cluster" "metal3-machine"={"Namespace":"default","Name":"dpu-cluster-controlplane-8h4dc"} "machine"="dpu-cluster-9vh7m"
I0811 07:15:49.786257       1 metal3machine_manager.go:733] controllers/Metal3Machine/Metal3Machine-controller "msg"="Updating machine" "cluster"="dpu-cluster" "machine"="dpu-cluster-9vh7m" "metal3-cluster"="dpu-cluster" "metal3-machine"={"Namespace":"default","Name":"dpu-cluster-controlplane-8h4dc"} 
E0811 07:15:49.787410       1 controller.go:317] controller/metal3machine "msg"="Reconciler error" "error"="failed to update BaremetalHost: host not found for machine dpu-cluster-9vh7m" "name"="dpu-cluster-controlplane-8h4dc" "namespace"="default" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="Metal3Machine" 
```

**What did you expect to happen:**

Associate Metal3Machine with BareMetalHost, and provision them.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: `clusterctl version: &version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.5", GitCommit:"d488bdb875d302eba85221fa35c9f13c00df4ae7", GitTreeState:"clean", BuildDate:"2022-07-04T13:59:55Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}`
- Cluster-api-provider-metal3 version:
- Environment (metal3-dev-env or other): on-prem env
- Kubernetes version: (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.2-rc.0.33+050f930f896887", GitCommit:"050f930f8968874855eb215f0c0f0877bcdaa0e8", GitTreeState:"clean", BuildDate:"2022-06-15T11:38:02Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"archive", BuildDate:"2022-06-13T11:38:54Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
```

/kind bug

### PR DESCRIPTION
**Pull request by k82cn**
Signed-off-by: Klaus Ma <klausm@nvidia.com>

**What this PR does / why we need it**:

If Metal3Machine's spec is in-correct, it's better to report this err instead of ignore it.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #682

### CODE REVIEW

**Comment by zhouhao3** [comment]
You also need to modify the corresponding UT.

**Comment by k82cn** [comment]
> You also need to modify the corresponding UT.

Sure, let me update UP accordingly :)

**Comment by mboukhalfa** [comment]
@k82cn can you please update the unit test accordingly

**Comment by k82cn** [comment]
> @k82cn can you please update the unit test accordingly

Sure, I'll update it ASAP :)

**Comment by furkatgofurov7** [comment]
@k82cn hi, since #693 is merged which was an alternative to fix the issue this PR is trying to fix, can you test with the latest CAPM3 and confirm if it has been solved?

**Comment by k82cn** [comment]
> @k82cn hi, since #693 is merged which was an alternative to fix the issue this PR is trying to fix, can you test with the latest CAPM3 and confirm if it has been solved?

Thanks for your feedback, that's ok to me :)

**Pull request closed without merging**
