### PR TITLE
⚠️ Remove v1alpha2 types

### PR DESCRIPTION
**Pull request by fmuyassarov**
**What this PR does / why we need it**:
Remove v1alpha2 types.
Fixes: https://github.com/metal3-io/cluster-api-provider-metal3/issues/159

### CODE REVIEW

**Review by maelk — APPROVED** [review]

**Comment by kashifest** [comment]
lgtm

**Review by furkatgofurov7 — COMMENTED** [review]
Tests have passed now, so merging it. 

/lgtm

**Comment by fmuyassarov** [comment]
We are going to have lazy consensus of two weeks to check if there are any objections on this.
1. Update on the Metal3 [mailing list](https://groups.google.com/u/1/g/metal3-dev/c/b58TApTm7AA) has been sent
2. Update on the [slack](https://kubernetes.slack.com/archives/CHD49TLE7/p1614764044053600) has been sent

**Comment by furkatgofurov7** [comment]
> **PLEASE DON'T MERGE THIS.**
> 
> We are going to have lazy consensus of two weeks to check if there are any objections on this.
> 
>     1. Update on the Metal3 [mailing list](https://groups.google.com/u/1/g/metal3-dev/c/b58TApTm7AA) has been sent
> 
>     2. Update on the [slack](https://kubernetes.slack.com/archives/CHD49TLE7/p1614764044053600) has been sent

Since the agreed lazy consensus date reached, this should be safe to merge. 

@fmuyassarov leaving it up to you to unhold. 

/lgtm

**Pull request merged**
