### PR TITLE
🐛 bump google.golang.org/protobuf to v1.33.0

### PR DESCRIPTION
**Pull request by tuminoid**
JSON unmarshalling can enter infinite loop.
https://osv.dev/vulnerability/GO-2024-2611

### CODE REVIEW

**Comment by tuminoid** [comment]
/test-centos-e2e-integration-main
/test-ubuntu-integration-main
Let's see if Cleura is broken

**Review by kashifest — COMMENTED** [review]
/approve

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Pull request merged**
