### PR TITLE
Fix typo in comment

### PR DESCRIPTION
**Pull request by fenggw-fnst**
Signed-off-by: Guangwen Feng <fenggw-fnst@cn.fujitsu.com>

### CODE REVIEW

**Comment by fmuyassarov** [comment]
Thanks. Would you mind to fix this one too in the same PR ?
 https://github.com/metal3-io/cluster-api-provider-metal3/blob/f43c80935472ae7f3550ab62f9aedcee0cecb8c9/config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datatemplates.yaml#L828

/ok-to-test

**Comment by fmuyassarov** [comment]
> Thanks. Would you mind to fix this one too in the same PR ?
> https://github.com/metal3-io/cluster-api-provider-metal3/blob/f43c80935472ae7f3550ab62f9aedcee0cecb8c9/config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datatemplates.yaml#L828
> 
> /ok-to-test



You can run `make generate-manifests` to have the same fix on the manifest.

**Comment by fenggw-fnst** [comment]
Sure, I have updated the PR, thanks for the review.

**Pull request merged**
