### PR TITLE
🌱 Bump CAPI to v1.7.0-beta.1

### PR DESCRIPTION
**Pull request by Sunnatillo**
as title says

### CODE REVIEW

**Review by tuminoid — COMMENTED** [review]
/lgtm

Needs #1572 to merge to fix the link check.

**Review by kashifest — COMMENTED** [review]
/approve

**Comment by kashifest** [comment]
@Sunnatillo can we take it out of draft ?

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Pull request merged**
