### PR TITLE
📖 Update Support matrix in Contributing guide

### PR DESCRIPTION
**Pull request by kashifest**
Adds v1.6.x and updates v1.4.x support timeline. v1.4.x is now EOL but will be tested for one more release cycle as promised in the contributing guide.

### CODE REVIEW

**Review by Sunnatillo — COMMENTED** [review]
/lgtm

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Review by lentzi90 — COMMENTED** [review]
/approve

**Pull request merged**
