### PR TITLE
🐛Only use redfish-virtualmedia for live-iso test (backport)

### PR DESCRIPTION
**Pull request by adilGhaffarDev**
Backporting live-iso fix to realease-1.1
https://github.com/metal3-io/cluster-api-provider-metal3/pull/690

### CODE REVIEW

**Comment by kashifest** [comment]
> /test-ubuntu-e2e-main /test-centos-e2e-main

why main?

**Comment by adilGhaffarDev** [comment]
> > /test-ubuntu-e2e-main /test-centos-e2e-main
> 
> why main?

my bad

**Review by furkatgofurov7 — COMMENTED** [review]
/lgtm

**Pull request merged**
