### PR TITLE
🌱 Bump the Golang version to 1.16

### PR DESCRIPTION
**Pull request by fmuyassarov**
**What this PR does / why we need it**:
Bump the Golang version to [1.16](https://blog.golang.org/go1.16)

### CODE REVIEW

**Review by kashifest — APPROVED** [review]

**Comment by fmuyassarov** [comment]
/hold cancel
since metal3-io/project-infra#172 is merged now.

**Review by furkatgofurov7 — COMMENTED** [review]
/lgtm

**Pull request merged**
