### PR TITLE
Restore the BMO config map and add more logs to the e2e pivoting test

### PR DESCRIPTION
**Pull request by namnx228**
This PR fixes the issue with the e2e pivoting test which is the same as the PR on m3-dev-env: https://github.com/metal3-io/metal3-dev-env/pull/765

### CODE REVIEW

**Comment by kashifest** [comment]
I will wait for the tests to pass before reviewing

**Review by mboukhalfa — APPROVED** [review]

**Comment by kashifest** [comment]
why is it failing the test?

**Comment by kashifest** [comment]
Is it waiting for #277 ?

**Comment by namnx228** [comment]
> Is it waiting for #277 ?
@kashifest Yes it was

**Review by kashifest — APPROVED** [review]

**Review by fmuyassarov — COMMENTED** [review]
/lgtm

**Pull request merged**
