### PR TITLE
🌱  Update e2e feature tests link

### PR DESCRIPTION
**Pull request by Sunnatillo**
Fixes markdown check action

### CODE REVIEW

**Comment by Sunnatillo** [comment]
We should override the tests as we are only changing readme file, I do not have a permission. Please override if you have permission

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Comment by tuminoid** [comment]
/override test-centos-e2e-integration-main test-ubuntu-integration-main 

> We should override the tests as we are only changing readme file, I do not have a permission. Please override if you have permission

Done.

**Pull request merged**
