### PR TITLE
🌱 Introduce gosec file for go security checks and related changes

### PR DESCRIPTION
**Pull request by kashifest**
This PR does the following:

-  [Add gosec file for go security checks](https://github.com/metal3-io/cluster-api-provider-metal3/pull/547/commits/cd604c0501b0fac636b813255c867e835473819b)
-  [Use crypto/rand instead of math/rand](https://github.com/metal3-io/cluster-api-provider-metal3/pull/547/commits/453ebbc0d71792062fb867d5cc5bcc6159512481)
-  [Cleanup bad filepath using filepath.Clean](https://github.com/metal3-io/cluster-api-provider-metal3/pull/547/commits/ce4348085dcd58610a41b951492bac927650e78f)
This is to get rid of the gosec vulnerability "Potential file inclusion via variable"

- [Fix unsafe defer call to file.Close()](https://github.com/metal3-io/cluster-api-provider-metal3/pull/547/commits/93bf7f8b5841d3e7a5b86aade356a9a8385762bb)
Fixes the go sec erro "Deferring unsafe method "Close" on type "*os.File""

- [Exclude rules G107 for gosec](https://github.com/metal3-io/cluster-api-provider-metal3/pull/547/commits/c1af331c2abd90f61b24aed73f56184c37b93eb5)
Currently the way URL is handled in downloadFile() function of test/e2e/commonn.go is causing an error, G107 (CWE-88): Potential HTTP request made with variable url. The only way to solve this is to call http.Get with a const URL value. Since this function is called from multiple files, its not possible to call it using const value of URL. Which is why currently we are excluding this rule. Once we find a more appropriate way, we shold remove this exclusion.

- [Reassign loop variable to address gosec G601](https://github.com/metal3-io/cluster-api-provider-metal3/pull/547/commits/a8cf6db0a7a5fcd51d6906d90c5b7735817bd921)
Use of loop variable address without reassigning causes G601 (CWE-118): Implicit memory aliasing in for loop.

- [Uplift golangci/golangci-lint v1.44.2](https://github.com/metal3-io/cluster-api-provider-metal3/pull/547/commits/f9db169f5b0de0146ec5e09aea5f829b5e3632e3)
- [Remove nolint:gosec](https://github.com/metal3-io/cluster-api-provider-metal3/pull/547/commits/5cedc2cf39dc3b350e1c353de9d6d3bb287ec7a1) 
This commit removes the error nolint:gosec` is unused for linter "gosec"

### CODE REVIEW

**Review by lentzi90 — APPROVED** [review]

**Comment by kashifest** [comment]
/hold
There seems to be some issues still present.

**Comment by kashifest** [comment]
/hold cancel
The problematic code has been fixed.

**Review by namnx228 — COMMENTED** [review]
/lgtm

**Review by furkatgofurov7 — APPROVED** [review]
Great work, thanks!

/approve

**Pull request merged**
