### PR TITLE
🌱 add KUBECTL_SHA256 passthru

### PR DESCRIPTION
**Pull request by tuminoid**
Pass thru KUBECTL_SHA256 from JJB for upgrade e2e tests.

Manual cherry-pick of #1178 adapted to release-1.4.

### CODE REVIEW

**Comment by tuminoid** [comment]
Unrelated test failure.

**Review by Sunnatillo — APPROVED** [review]
/lgtm

**Review by lentzi90 — COMMENTED** [review]
/approve

**Comment by tuminoid** [comment]
OK, it might help that we merge 1.4 integration job in JJB first :)

/test-ubuntu-e2e-integration-release-1-4

**Pull request merged**
