### PR TITLE
🌱 Bump kustomize version to 3.9.1

### PR DESCRIPTION
**Pull request by fmuyassarov**
**What this PR does / why we need it**:
Bump kustomize version to 3.9.1

### CODE REVIEW

**Comment by furkatgofurov7** [comment]
Not sure if it is failing because of [this](https://github.com/metal3-io/cluster-api-provider-metal3/blob/master/hack/ensure-kustomize.sh#L22) needed to be updated or something else? or it was just a flake in CI :/

**Comment by kashifest** [comment]
IMO we should keep the kustomize version close to CAPI's allowed kustomize to keep the sync, is there any specific reason we are bumping it to newest ?

**Comment by fmuyassarov** [comment]
> IMO we should keep the kustomize version close to CAPI's allowed kustomize to keep the sync, is there any specific reason we are bumping it to newest ?

I have updated this version in CAPI as well (PR isn't merged yet though). No specific reason, just to sync with the latest + with CAPI's version.

**Comment by kashifest** [comment]
> > IMO we should keep the kustomize version close to CAPI's allowed kustomize to keep the sync, is there any specific reason we are bumping it to newest ?
> 
> I have updated this version in CAPI as well (PR isn't merged yet though). No specific reason, just to sync with the latest + with CAPI's version.

Then I guess lets wait for CAPI to merge it and then we can test this PR again. I believe we need to change the same in m3-dev-env also (I dnt remember if we install it there or we use CAPI/CAPM3 kustomize)

**Comment by furkatgofurov7** [comment]
> Then I guess lets wait for CAPI to merge it and then we can test this PR again. I believe we need to change the same in m3-dev-env also (I dnt remember if we install it there or we use CAPI/CAPM3 kustomize)

In metal3-dev-env we install it directly I believe.

**Comment by fmuyassarov** [comment]
> > > IMO we should keep the kustomize version close to CAPI's allowed kustomize to keep the sync, is there any specific reason we are bumping it to newest ?
> > 
> > 
> > I have updated this version in CAPI as well (PR isn't merged yet though). No specific reason, just to sync with the latest + with CAPI's version.
> 
> Then I guess lets wait for CAPI to merge it and then we can test this PR again. I believe we need to change the same in m3-dev-env also (I dnt remember if we install it there or we use CAPI/CAPM3 kustomize)

Sure. Just interested to know, why do you think we need to wait until it gets merged in CAPI? Are there some dependencies?

**Comment by kashifest** [comment]
> > > > IMO we should keep the kustomize version close to CAPI's allowed kustomize to keep the sync, is there any specific reason we are bumping it to newest ?
> > > 
> > > 
> > > I have updated this version in CAPI as well (PR isn't merged yet though). No specific reason, just to sync with the latest + with CAPI's version.
> > 
> > 
> > Then I guess lets wait for CAPI to merge it and then we can test this PR again. I believe we need to change the same in m3-dev-env also (I dnt remember if we install it there or we use CAPI/CAPM3 kustomize)
> 
> Sure. Just interested to know, why do you think we need to wait until it gets merged in CAPI? Are there some dependencies?



> Sure. Just interested to know, why do you think we need to wait until it gets merged in CAPI? Are there some dependencies?

Then we would know if we need to change something from our side regarding the way kustomize is used in m3-dev-env. If you remember CAPI's 3.5.5 was not able to kustomize CAPM3. We needed to use 3.8.x to get it work.

**Review by kashifest — APPROVED** [review]
/test-integration

**Comment by fmuyassarov** [comment]
Could it be that this is failing due the actual Kustomize version we install in dev-env? It is [3.8.5](https://github.com/metal3-io/metal3-dev-env/blob/cb568d3cfec1c1fa23f9ee847b9a05e290ce2144/lib/common.sh#L198) in there. Seems I need to update it there first to pass the integration test here.

**Comment by fmuyassarov** [comment]
/close
This is already done  by @kashifest

**Pull request closed without merging**
