### PR TITLE
📖 improve release notes generator

### PR DESCRIPTION
**Pull request by tuminoid**
Manual cherry pick of #1177.

### CODE REVIEW

**Comment by tuminoid** [comment]
/test-ubuntu-e2e-integration-release-1-4
Would you start the test please.

**Comment by tuminoid** [comment]
/test-ubuntu-e2e-integration-release-1-4
Would you start the test please.

**Review by lentzi90 — COMMENTED** [review]
/approve

**Review by Sunnatillo — APPROVED** [review]
/lgtm

**Pull request merged**
