### PR TITLE
🌱 Replace deprecated clusterCacheTracker with clusterCache

### PR DESCRIPTION
**Pull request by Sunnatillo**
This PR replaces deprecated clusterCacheTracker with new clusterCache

### CODE REVIEW

**Comment by Sunnatillo** [comment]
/test metal3-ubuntu-e2e-integration-test-main
tcp error

**Comment by Sunnatillo** [comment]
/cc @mquhuy 
We need to take this before v1.9 release

**Review by kashifest — COMMENTED** [review]
/approve

**Pull request merged**
