### PR TITLE
🌱 Add inegration test trigger to the README

### PR DESCRIPTION
**Pull request by mboukhalfa**

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Review by Sunnatillo — COMMENTED** [review]
LTGM

**Review by kashifest — APPROVED** [review]

**Comment by mboukhalfa** [comment]
@lentzi90  can you re LGTM - rebased

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Pull request merged**
