### PR TITLE
🌱 Uplift controller runtime

### PR DESCRIPTION
**Pull request by furkatgofurov7**
**What this PR does / why we need it**:
Uplifts ControllerRuntime to v0.9.7
CAPI has already uplifted to above version.

### CODE REVIEW

**Review by namnx228 — APPROVED** [review]
LGTM

**Comment by smoshiur1237** [comment]
LGTM

**Review by kashifest — APPROVED** [review]

**Review by fmuyassarov — COMMENTED** [review]
/test-centos-integration
/test-v1a5-e2e
/test-v1a5-centos-e2e
/lgtm

**Pull request merged**
