### PR TITLE
🌱 Bump CAPI to v1.5.3

### PR DESCRIPTION
**Pull request by kashifest**
Bumping it manually since it seems dependabot has only caught the test/ module bump.

### CODE REVIEW

**Comment by tuminoid** [comment]
> Bumping it manually since it seems dependabot has only caught the test/ module bump.

Yeah, and it doesn't do readme fixes either etc.
/lgtm

**Review by smoshiur1237 — APPROVED** [review]
/lgtm

**Review by lentzi90 — COMMENTED** [review]
/approve

**Pull request merged**
