### PR TITLE
🌱 remove redundant make targets and scripts

### LINKED ISSUE #1547: Remove gofmt make targets and script [CAPM3]
We use golangci-lint that includes gosec, gofmt and govet already. These redundant checks should be removed. Remove them from the [Makefile](https://github.com/metal3-io/cluster-api-provider-metal3/blob/7d289d9ac9aa4d928ac4bbd8cf0b4eef92bd3cac/Makefile#L276-L286) and remove the redundant scripts in [hack](https://github.com/metal3-io/cluster-api-provider-metal3/tree/main/hack).

### PR DESCRIPTION
**Pull request by alexandremahdhaoui**
**What this PR does / why we need it**:
- remove redundant make targets and associated scripts

**Which issue(s) this PR fixes**:
Fixes #1547

### CODE REVIEW

**Review by kashifest — COMMENTED** [review]
Thanks a lot for the PR. You need to remove `fmt` from `test` phony as well https://github.com/metal3-io/cluster-api-provider-metal3/blob/main/Makefile#L137

**Review by tuminoid — COMMENTED** [review]
/lgtm

Thanks for the contribution!

**Pull request merged**
