### PR TITLE
🌱 Add and update unit tests for metal3remediation manager.

### PR DESCRIPTION
**Pull request by adilGhaffarDev**
This PR adds following unit tests for metal3remediation_manager:

 - GetUnhealthyHost (new entries added)
 - SetUnhealthyAnnotation
 - SetRebootAnnotation
 - TimeToRemediate

41.2 -->> 74% coverage is done.

### CODE REVIEW

**Review by kashifest — APPROVED** [review]

**Review by smoshiur1237 — COMMENTED** [review]
/lgtm

**Pull request merged**
