### PR TITLE
:seedling: Add labels on e2e tests

### LINKED ISSUE #1485: Label e2e tests in CAPM3
This issue is reserved for the KubeCon EU 2024 contrib-fest. Please do not work on it before 2024-03-20.

Our [e2e tests](https://github.com/metal3-io/cluster-api-provider-metal3/tree/main/test/e2e) currently have descriptions that include markers like `[basic]` or `[integration]` (see for example [this](https://github.com/metal3-io/cluster-api-provider-metal3/blob/b207bcd07be1eb7ba4a504c197383f65ec86348c/test/e2e/basic_integration_test.go#L12)). We use them to select subsets of tests to run. So we can run only tests that have a description matching `[basic]` for example.
There is a better way to [label ginkgo tests](https://onsi.github.io/ginkgo/#spec-labels) now and we should adopt it.

The initial task is simple: add labels to the tests matching the markers that we currently have.
For example [this](https://github.com/metal3-io/cluster-api-provider-metal3/blob/b207bcd07be1eb7ba4a504c197383f65ec86348c/test/e2e/basic_integration_test.go#L12)

```go
var _ = Describe("When testing basic cluster creation [basic]", func() {
```

should be changed to

```go
var _ = Describe("When testing basic cluster creation [basic]", Label("basic"), func() {
```

### PR DESCRIPTION
**Pull request by lekaf974**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1485

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
/approve

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Pull request merged**
