### PR TITLE
🐛Rename unused BMH state mentions in e2e tests

### PR DESCRIPTION
**Pull request by furkatgofurov7**
**What this PR does / why we need it**:
To be fully compliant in e2e tests with respect to the efforts on https://github.com/metal3-io/baremetal-operator/pull/340

### CODE REVIEW

**Comment by furkatgofurov7** [comment]
I am skipping running e2e tests on this PR on purpose since it is changing only log messages, and if you think otherwise please let me know.

/test-v1b1-integration

**Review by kashifest — APPROVED** [review]

**Review by namnx228 — COMMENTED** [review]
/lgtm

**Pull request merged**
