### PR TITLE
🌱 remove kubesec workflow

### PR DESCRIPTION
**Pull request by tuminoid**
Kubesec action has not been maintained for 3+ years and is broken. Kubesec itself is maintained, and we'll see if we reintroduce it as prow test instead of action later, or if we have enough coverage from existing tools.

### CODE REVIEW

**Comment by tuminoid** [comment]
/override metal3-centos-e2e-integration-test-main  metal3-ubuntu-e2e-integration-test-main

**Review by kashifest — COMMENTED** [review]
/approve
/cc @smoshiur1237

**Review by Sunnatillo — COMMENTED** [review]
/lgtm

**Pull request merged**
