### PR TITLE
🐛 Fix for v1.6 clusterctl upgrade.

### PR DESCRIPTION
**Pull request by kashifest**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by kashifest** [comment]
@adilGhaffarDev @tuminoid dont ask me why and how the tests are running

**Comment by tuminoid** [comment]
> @adilGhaffarDev @tuminoid dont ask me why and how the tests are running

Clearly the Jenkins had disabled the jobs for the previous PR. We've seen that sometimes.

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Comment by kashifest** [comment]
Not sure now if I can self approve this PR although the commit is from @adilGhaffarDev 
/approve

**Pull request merged**
