### PR TITLE
🌱 remove hack/gosec.sh

### PR DESCRIPTION
**Pull request by tuminoid**
Gosec runs now as part of golangci-lint suite, the old hack script is obsolete.

Needs https://github.com/metal3-io/project-infra/pull/578 to be merged first.
/hold

### CODE REVIEW

**Comment by tuminoid** [comment]
/override test-centos-e2e-integration-main 
/override test-ubuntu-integration-main 

Integration tests are unrelated.

**Review by lentzi90 — COMMENTED** [review]
/approve

**Review by smoshiur1237 — COMMENTED** [review]
/lgtm

**Pull request merged**
