### PR TITLE
🌱 Install setup-envtest from controller-runtime release directly and Bump envtest version to v1.31.0

### PR DESCRIPTION
**Pull request by kashifest**
This PR changes the way to install setup-envtest from controller-runtime release directly instead of downloading it from go modules and also bumps the envtest kubernetes version to v1.31.0. Please check for https://github.com/kubernetes-sigs/controller-runtime/pull/2811 for more information.

### CODE REVIEW

**Review by tuminoid — COMMENTED** [review]
Nit + can you add to description which problem this solves?

**Review by tuminoid — COMMENTED** [review]
/approve

**Review by Sunnatillo — COMMENTED** [review]
/lgtm

**Pull request merged**
