### PR TITLE
🌱 Uplift capi to v1.2.9

### PR DESCRIPTION
**Pull request by furkatgofurov7**
**What this PR does / why we need it**:
https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.2.9

### CODE REVIEW

**Comment by furkatgofurov7** [comment]
/hold

we need to take https://github.com/metal3-io/cluster-api-provider-metal3/pull/831 in first

**Review by kashifest — APPROVED** [review]

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Comment by furkatgofurov7** [comment]
running e2e tests to be sure
/hold cancel

**Pull request merged**
