### PR TITLE
🌱 bump IPAM to v1.5.0

### PR DESCRIPTION
**Pull request by tuminoid**
Bump IPAM to newly released v1.5.0.

### CODE REVIEW

**Review by smoshiur1237 — COMMENTED** [review]
/lgtm

**Comment by tuminoid** [comment]
Had to rebase as BMO bump touched same files. Please re-add flags.

/test-centos-e2e-integration-main
/test-ubuntu-integration-main

**Review by smoshiur1237 — APPROVED** [review]
/lgtm

**Pull request merged**
