### PR TITLE
⚠️ Drop CAPM3 v1alpha4 support from main branch

### LINKED ISSUE #508: Drop v1alpha4 support on main branch
Based on https://cluster-api.sigs.k8s.io/contributing?highlight=support#support-and-guarantees, CAPI is planning to stop supporting API version v1alpha3 (CAPM3 v1alpha4 compatible) from 2022-02-23. 
The notice to drop the CAPM3 v1a4 support was given during the metal3 community meeting on 2022-01-26, this is the issue created for visibility and get to know if there are any objections to these changes from the wider scope of the users of CAPM3.

**Note:** v1a4 API types will be removed only from the main branch, and people using it can always rely on one of the releases from the release branch [release-0.4](https://github.com/metal3-io/cluster-api-provider-metal3/tree/release-0.4) if needed.

### PR DESCRIPTION
**Pull request by furkatgofurov7**
**What this PR does / why we need it**:

- Removes v1alpha4 API types, conversion gen from Makefile, and label from crd kustomization file
- updates root README with dropping support notes,
- Updates code-gen script and metadata.yaml 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #508 

/hold
until notice is given in the bare-metal slack channel and metal3 mailing list and it is over.

### CODE REVIEW

**Comment by furkatgofurov7** [comment]
**Please don't unhold**. 
This has been brought up at the metal3 community meeting on 9.2.2022 and 2 weeks of lazy consensus was given in order to reach enough people and community members before moving with these changes.

**Comment by furkatgofurov7** [comment]
> hold
> until notice is given in the bare-metal slack channel and metal3 mailing list and it is over.

Notice period has ended today and there were no objections till now on this PR/ slack channel or mailing list, so unholding it.

/hold cancel

**Review by lentzi90 — APPROVED** [review]

**Review by smoshiur1237 — APPROVED** [review]
/lgtm

**Pull request merged**
