### PR TITLE
🌱 use GLOBIGNORE to ignore hack/tools/go.mod in verify-release.sh

### PR DESCRIPTION
**Pull request by tuminoid**
Using GLOBIGNORE makes the code simpler, and allows us to ignore the hack/tools/go.mod for sed as well, not just in grep. This fixes issue that module versions are reported as incorrect, if hack/tools/go.mod is the one with wrong version, yet the output then does now show the hack/tools/go.mod as culprit.

### CODE REVIEW

**Comment by tuminoid** [comment]
/override test-ubuntu-e2e-integration-release-1-4
Save the trees.

**Review by kashifest — COMMENTED** [review]
/approve

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Comment by tuminoid** [comment]
/test build
Prow fails to communicate the success back to GH, it seems ....

**Comment by tuminoid** [comment]
/test build
Maybe now the rate limit is refreshed?

**Comment by tuminoid** [comment]
/override build

Build is stuck on different commit `e5d999` than others `1510c8`, doesn't react to anything when fixing it, and it is not relevant test here since we're only changing a hack script.

**Comment by tuminoid** [comment]
/override test-ubuntu-e2e-integration-release-1-4 
Repushed for Prow issues.

**Pull request merged**
