### PR TITLE
Add default Metal3DataTemplate to example

### PR DESCRIPTION
**Pull request by ileixe**
**What this PR does / why we need it**

User would be confused when they want to try metal3 provider for the first time. Add naive default to create Machine correctly at least.

**Which issue(s) this PR fixes**

Fixes https://github.com/metal3-io/cluster-api-provider-metal3/issues/820

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
Thanks for the PR!
This looks good to me :slightly_smiling_face: 
/lgtm

**Review by kashifest — APPROVED** [review]

**Pull request merged**
