### PR TITLE
🐛 Use consistent spelling for Ironic

### PR DESCRIPTION
**Pull request by furkatgofurov7**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by namnx228 — COMMENTED** [review]
LGTM

**Review by fmuyassarov — COMMENTED** [review]
/lgtm

**Pull request merged**
