### PR TITLE
🌱 improve hack/verify-release.sh

### PR DESCRIPTION
**Pull request by tuminoid**
Few improvements from previous minor release cycle:

- change artefact to artifact for more common spelling
- match container image detection from release notes to match the earlier change in the release tooling
- rename some of the titles to be more descriptive
- mutate go.mod files for osv-scanner so it can accurately report vulnerablities in golang stdlib (ie. mutate "go 1.21" directive to "go 1.21.9" with patch version read off from main Dockerfile
- check version of osv-scanner, <1.5.0 give weird warnings now
- make docker pull gcrane and osv-scanner images always, so it uses the newest versions

Same as/adapted [BMO #1691](https://github.com/metal3-io/baremetal-operator/pull/1691)

### CODE REVIEW

**Review by smoshiur1237 — COMMENTED** [review]
/lgtm

**Comment by tuminoid** [comment]
/override metal3-centos-e2e-integration-test-main  metal3-ubuntu-e2e-integration-test-main

**Review by lentzi90 — COMMENTED** [review]
/approve

**Review by adilGhaffarDev — COMMENTED** [review]
/lgtm

**Pull request merged**
