### PR TITLE
✨ Support CustomDeploy in addition to Image

### PR DESCRIPTION
**Pull request by dtantsur**
BMO supports `CustomDeploy` [1] as an alternative way to provision hosts. We use it in OpenShift to invoke our custom deploy step that runs `coreos-installer`. CAPM3 only supports setting the `Image` field as part of the Metal3Machine template. This change adds support for `CustomDeploy` as well, making `Image` optional in this case.

[1] https://github.com/metal3-io/metal3-docs/blob/main/design/baremetal-operator/deploy-steps.md

Signed-off-by: Dmitry Tantsur <dtantsur@protonmail.com>

### CODE REVIEW

**Review by tuminoid — COMMENTED** [review]
Would you please add a proper description to this PR?

**Comment by dtantsur** [comment]
@tuminoid what sort of information are you looking for? For me the subject is self-explanatory, to be honest.

**Comment by dtantsur** [comment]
@tuminoid thanks, done!

**Comment by tuminoid** [comment]
> @tuminoid thanks, done!

Thanks, really helpful description now. :+1:

**Review by lentzi90 — COMMENTED** [review]
/approve
It would be really nice to have an e2e test with Fedora CoreOS either here or in BMO to verify and show as example!

**Comment by dtantsur** [comment]
> It would be really nice to have an e2e test with Fedora CoreOS either here or in BMO to verify and show as example!

Unfortunately, it's not enough to use Fedora CoreOS: you need an IPA image with a plugin.

**Comment by tuminoid** [comment]
@mboukhalfa @kashifest PTAL

**Comment by Rozzii** [comment]
/lgtm
Thank you!

**Pull request merged**
