### PR TITLE
🐛 Image validation requiring urls for checksum

### LINKED ISSUE #692: image checksum can no longer be set to a hash
**What steps did you take and what happened:**
Set `spec.image.checksum` of `Metal3Machine` to a md5 hash. The m3m is deemed invalid and reconciliation is aborted.

**What did you expect to happen:**
The machine gets reconciled and the hash is used for verification, as per its [description](https://github.com/metal3-io/cluster-api-provider-metal3/blob/main/api/v1beta1/common_types.go#L61).

**Anything else you would like to add:**
Introduced by https://github.com/metal3-io/cluster-api-provider-metal3/pull/604/files#diff-90dc8b367863881133b9eb436059164daeadba015bed7d4124e6ea3c18828a2aR102

**Environment:**

- Cluster-api-provider-metal3 version: 1.1.2

/kind bug

### PR DESCRIPTION
**Pull request by schrej**
Cherry Pick of #693

What this PR does / why we need it:
Due to a recent change, the Image.Checksum field only accepted URLs and not checksums directly. This PR fixes that, and applies the same validation for Metal3MachineTemplate and Metal3Machine.

It fixes a few minor linter complaints as well.

Which issue(s) this PR fixes:
Fixes #692

### CODE REVIEW

**Comment by furkatgofurov7** [comment]
You can ignore go mod failure for now, should be fixed after https://github.com/metal3-io/cluster-api-provider-metal3/pull/731

**Comment by furkatgofurov7** [comment]
@schrej can you please rebase this PR please, 731 got merged. I would like to take this in before having a patch release which we scheduled for today.

**Review by furkatgofurov7 — APPROVED** [review]
Thanks!

/retitle 🐛 Image validation requiring urls for checksum
(we usually omit release branch names in the cherry-pick PR titles)
/cc @kashifest @lentzi90

**Comment by furkatgofurov7** [comment]
Too much trigegrs to remember :)

> /test-e2e-ubuntu-release-1-1

 /test-ubuntu-e2e-release-1-1

**Comment by schrej** [comment]
> Too much triggers to remember :)
> 
> > /test-e2e-ubuntu-release-1-1
> 
> /test-ubuntu-e2e-release-1-1

Was looking for the commands yesterday (though I'm not sure if I can even trigger them), maybe the list could use an update: https://github.com/metal3-io/project-infra/tree/main/jenkins#commands

**Comment by furkatgofurov7** [comment]
> Was looking for the commands yesterday (though I'm not sure if I can even trigger them), maybe the list could use an update: https://github.com/metal3-io/project-infra/tree/main/jenkins#commands

sorry for that, usually we keep e2e test triggers in the root readme of this repo, but we forgot to document release-1.1 branch triggers. I am taking care of it in https://github.com/metal3-io/cluster-api-provider-metal3/pull/730/files and will back-port it to release-1.1 branch.

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Comment by kashifest** [comment]
> Was looking for the commands yesterday (though I'm not sure if I can even trigger them), maybe the list could use an update: https://github.com/metal3-io/project-infra/tree/main/jenkins#commands

I have invited you to Metal3 org.Do make sure that your profile is public.

**Comment by furkatgofurov7** [comment]
> I have invited you to Metal3 org.Do make sure that your profile is public.

@schrej this should remove the need for `ok-to-test` label when ever you push a new PR to the Metal3 repositories and possibly also trigger the CI next time.

**Pull request merged**
