### PR TITLE
🌱 Fixing and simplifying clusterctl upgrade tests

### PR DESCRIPTION
**Pull request by adilGhaffarDev**
**What this PR does / why we need it**:
Fixing and simplifying clusterctl upgrade tests.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by adilGhaffarDev** [comment]
test-e2e-clusterctl-upgrade-release-1-6

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Review by mboukhalfa — APPROVED** [review]

**Pull request merged**
