### PR TITLE
🌱Uplift IPAM v1.5.2 and BMO v0.4.1 patch release

### PR DESCRIPTION
**Pull request by smoshiur1237**
Uplift IPAM v1.5.2 and BMO v0.4.1 patch release

### CODE REVIEW

**Review by Sunnatillo — DISMISSED** [review]
/lgtm

**Review by lentzi90 — COMMENTED** [review]
/approve

**Comment by kashifest** [comment]
it seems like this has common changes with #1333 or #1334.  can you check if you have included all the changes so that we can perhaps close this PRs

**Comment by smoshiur1237** [comment]
@kashifest yes I have those changes added in this PR.

**Pull request merged**
