### PR TITLE
:bug: Protect Metal3Data and Metal3DataClaim with Finalizers

### LINKED ISSUE #1356: Metal3Data deletable while in-use
**What steps did you take and what happened:**

1. Create a Cluster with Metal3 for infra and include a Metal3DataTemplate
2. Wait for all Machines to be Ready
3. Delete a Metal3Data or Metal3DataClaim
4. The Metal3Data or Metal3DataClaim is directly deleted, including the rest of the objects in the owner chain (Metal3DataClaim, Metal3Data, IPClaim, IPAddress and secrets for metadata and network data)

**What did you expect to happen:**

The objects should be protected from deletion while in use, i.e. even when deletion is triggered they should have finalizers that their controllers do not remove if they are still in-use.

**Environment:**

- Cluster-api version: v1.5.3
- Cluster-api-provider-metal3 version: v1.5.2
- Ip-address-manager: v1.5.2
- Environment (metal3-dev-env or other): other
- Kubernetes version: (use `kubectl version`): v1.28.3

/kind bug

### PR DESCRIPTION
**Pull request by maxrantil**
**What this PR does / why we need it**:
As the title describes. 

**Which issue(s) this PR fixes** 
Fixes #1356

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
This looks good! I want to try it out manually before approving though to make sure that the issue is truly solved.

**Comment by lentzi90** [comment]
The Metal3Machine manager is responsible for creating and deleting the Metal3DataClaims used by the Metal3Machines. To make sure that the Metal3DataClaim is protected (and cleaned up properly), we now add a finalizer when the Metal3DataClaim is created and remove it when cleaning up.

Similarly, the Metal3DataTemplate manager is responsible for the Metal3Data. It now also adds a finalizer when creating Metal3Data and removes it when cleaning up.

I have checked manually that this solves the issue.

**Comment by lentzi90** [comment]
Updated with a second commit that checks if the consumer is gone before proceeding with the deletion.
For the Metal3Data it is quite straight forward to, but for the Metal3DataClaim I had to go through the owner references... That is not ideal but I could not find another way to check the Metal3Machine. Any suggestions?

**Review by Sunnatillo — COMMENTED** [review]
/lgtm

**Comment by lentzi90** [comment]
Centos tests are unfortunately broken at the moment...

**Review by kashifest — COMMENTED** [review]
/approve

**Pull request merged**
