### PR TITLE
📖  Add note about node<--->bmh mapping after pivoting

### LINKED ISSUE #70: Node.Spec.ProviderID not updated after Move
After a clusterctl move from say a bootstrap cluster to a target cluster, the K.Node.Spec.ProviderID still contains the UID of the old BMH object. 

Simply updating the Node.Spec.ProviderID is not currently allowed as validation checks prevent Node.Spec.ProviderID to be changed after it has been set to a non-nil value (see https://github.com/kubernetes/kubernetes/pull/51761) 
	```Forbidden: node updates may not change providerID except from "" to valid, []: ```

Possible Solutions:
	1) Provide an option to have ProviderID be something other than UID of BMH -- for example: BMH 'Namespace/Name' may be unique for most environments. 
	2) Don’t use BMH.UID which is generated automatically during object creation but instead create a new field (say BMH.ProviderID) that we can populate with a random id. This field would be copied over as part of the move.
	3) Open an issue with K/K to allow updates to Node.Spec.ProviderID -- ie. Relax the validation checks.

/kind bug

xref: https://github.com/metal3-io/baremetal-operator/issues/431
@kashifest @maelk

### PR DESCRIPTION
**Pull request by furkatgofurov7**
**What this PR does / why we need it**:
This PR adds note regarding mapping K.Node <--> BMH after pivoting
 
**Which issue(s) this PR fixes**:
Fixes #70

### CODE REVIEW

**Review by maelk — APPROVED** [review]

**Review by fmuyassarov — COMMENTED** [review]
/lgtm

**Pull request merged**
