### PR TITLE
:book: Update job triggers documents

### PR DESCRIPTION
**Pull request by mquhuy**
Update job triggers after release-1.8

### CODE REVIEW

**Review by tuminoid — COMMENTED** [review]
/approve

**Review by Sunnatillo — APPROVED** [review]
/lgtm

**Review by Sunnatillo — APPROVED** [review]
/lgtm

**Comment by Sunnatillo** [comment]
/override metal3-centos-e2e-integration-test-main
//override metal3-ubuntu-e2e-integration-test-main

**Pull request merged**
