### PR TITLE
🌱 Uplift IPAM to v1.6.2 and BMO to v0.5.1

### PR DESCRIPTION
**Pull request by smoshiur1237**
Adding IPAM v1.6.2 and BMO v0.5.1

### CODE REVIEW

**Comment by smoshiur1237** [comment]
/hold 
waiting for BMO release

**Comment by tuminoid** [comment]
> /hold waiting for BMO release

Adding BMO to same PR?

**Review by Sunnatillo — COMMENTED** [review]
/lgtm

**Review by Sunnatillo — COMMENTED** [review]
/retitle 🌱 Uplift IPAM to 1.6.2 and BMO to v0.5.1

/lgtm

**Review by adilGhaffarDev — APPROVED** [review]

**Pull request merged**
