### PR TITLE
🐛 Fix running e2e upgrade tests with pre-releases

### PR DESCRIPTION
**Pull request by furkatgofurov7**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
Looks good! Just needs to drop the test commit.

**Review by kashifest — APPROVED** [review]

**Comment by furkatgofurov7** [comment]
https://github.com/metal3-io/metal3-dev-env/pull/1105 is merged, I'll remove the test commit and just run integration test here.

**Comment by furkatgofurov7** [comment]
Test commit is removed. 

/test-ubuntu-integration-main

cc @lentzi90

**Pull request merged**
