### PR TITLE
🌱 Uplift CAPI to v1.8.0-rc.0

### PR DESCRIPTION
**Pull request by adilGhaffarDev**
**What this PR does / why we need it**:
Uplift CAPI to v1.8.0-rc.0
This PR also removes TLS tests and relies on cluster API ManagerOptions to set TLS flags. TLS tests are already there in CAPI so we don't need to test it again on our side.
ref PR: https://github.com/kubernetes-sigs/cluster-api/pull/10883/files

### CODE REVIEW

**Comment by adilGhaffarDev** [comment]
passed for once: https://jenkins.nordix.org/view/Metal3/job/metal3-e2e-clusterctl-upgrade-test-main/75/
running it again just to confirm:
/test metal3-e2e-clusterctl-upgrade-test-main

**Comment by adilGhaffarDev** [comment]
passed 2nd time too: https://jenkins.nordix.org/view/Metal3/job/metal3-e2e-clusterctl-upgrade-test-main/76/
running one last time
 /test metal3-e2e-clusterctl-upgrade-test-main

**Comment by adilGhaffarDev** [comment]
this PR superseding this one: https://github.com/metal3-io/cluster-api-provider-metal3/pull/1845
lets close: https://github.com/metal3-io/cluster-api-provider-metal3/pull/1845 , when this is merged.

**Comment by adilGhaffarDev** [comment]
cc @smoshiur1237 @Sunnatillo

**Comment by adilGhaffarDev** [comment]
cc @smoshiur1237 @Sunnatillo

**Review by Sunnatillo — COMMENTED** [review]
/approve

**Comment by smoshiur1237** [comment]
Clusterctl upgrade, basic e2e and feature test pivoting passed already.
/lgtm

**Pull request merged**
