### PR TITLE
🌱 Add lint-fix as make target

### LINKED ISSUE #1546: Add make target for fixing linter errors
Add `make lint-fix` that runs `golangci-lint` with the `--fix` flag to automatically fix linting errors when possible.
Check how [CAPI has done it](https://github.com/kubernetes-sigs/cluster-api/blob/4c1fc0e6da848d4d8bdd5180917d547c6a29a5f4/Makefile#L658-L671) by reusing the lint target and adding the flag.

### PR DESCRIPTION
**Pull request by tico88612**
**What this PR does / why we need it**:
- Add auto fix golang lint via make target

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1546

### CODE REVIEW

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Review by lentzi90 — APPROVED** [review]
Worked like a charm! Thank you!
/approve

**Pull request merged**
