### PR TITLE
Fix wrong comment about Metal3DataClaim

### PR DESCRIPTION
**Pull request by MaXinjian**
Signed-off-by: Ma Xinjian <maxj.fnst@cn.fujitsu.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by maelk — APPROVED** [review]

**Comment by maelk** [comment]
/lgtm cancel
Please fix the linting errors

**Comment by fmuyassarov** [comment]
Please also remove default text in the commit message if you don't need it.

**Review by maelk — APPROVED** [review]
/lgtm

**Pull request merged**
