### PR TITLE
📖 getting-started: clean up ironic bits

### PR DESCRIPTION
**Pull request by dtantsur**
Explain the deploy ramdisk in a cleaner way.
Use consistent spelling for Ironic (upper case).

### CODE REVIEW

**Comment by furkatgofurov7** [comment]
Thanks for the patch @dtantsur. Regarding the consistency, we could fix also all other occurrences of 'Ironic' in other documents in the same patch, maybe? Here is the list of docs I found mentioning it (might not be full list though): 

- https://github.com/metal3-io/cluster-api-provider-metal3/blob/master/docs/architecture.md
- https://github.com/metal3-io/cluster-api-provider-metal3/blob/master/docs/deployment_workflow.md
- https://github.com/metal3-io/cluster-api-provider-metal3/blob/master/docs/dev-setup.md

**Comment by dtantsur** [comment]
I don't disagree with that, but I don't have time to go through other documents, unfortunately.

**Comment by furkatgofurov7** [comment]
@dtantsur can you please fix the markdown issue? Then, this can go as it is, and making consistent all other occurrences of 'Ironic' in other documents will be tackled in #202.

**Review by fmuyassarov — COMMENTED** [review]
/lgtm

**Review by kashifest — APPROVED** [review]

**Comment by kashifest** [comment]
@dtantsur you need to take care of the `markdownlint` error. Thanks for explaining ramdisk.

**Review by furkatgofurov7 — COMMENTED** [review]
/lgtm

**Pull request merged**
