### PR TITLE
🌱 Don't update BMH automatedCleaningMode if it is set to nil in M3M

### PR DESCRIPTION
**Pull request by fmuyassarov**
**What this PR does / why we need it**:
Fixes https://github.com/metal3-io/cluster-api-provider-metal3/issues/410

### CODE REVIEW

**Comment by fmuyassarov** [comment]
We need to add/update (if exists) documentation/instructions on using this feature. And I would like to do it on a follow up PR.

**Comment by fmuyassarov** [comment]
I will also take care of backporting it to release-1.0 & main branches. We can't use prow cherrypicker magic though, because those branches include new API types, so some manual work required.

**Review by furkatgofurov7 — COMMENTED** [review]
/lgtm

**Comment by fmuyassarov** [comment]
Backport to main branch is submitted in https://github.com/metal3-io/cluster-api-provider-metal3/pull/414.

**Pull request merged**
