### PR TITLE
🌱 Uplift CAPI to v1.2.6

### PR DESCRIPTION
**Pull request by mquhuy**
**What this PR does / why we need it**:
Uplifts CAPI to the latest patch release, which includes security fixes.

### CODE REVIEW

**Comment by kashifest** [comment]
You need to do `go mod tidy` in all the dirs you have changed go mod files. Seems `api/go.sum` changes are missing.

**Review by furkatgofurov7 — APPROVED** [review]
/retitle 🌱 Uplift CAPI to v1.2.6
/approve

**Pull request merged**
