### PR TITLE
🌱 Uplift BMO to release-0.6 and IPAM to v1.7.0

### PR DESCRIPTION
**Pull request by mquhuy**
As titled
/hold

### CODE REVIEW

**Comment by adilGhaffarDev** [comment]
let's add IPAM uplift also on this PR once we have the release.

**Review by Sunnatillo — COMMENTED** [review]
/lgtm

**Comment by mquhuy** [comment]
/retitle 🌱 Uplift BMO to release-0.6 and IPAM to v1.7.0

**Review by Sunnatillo — COMMENTED** [review]
/lgtm

**Comment by adilGhaffarDev** [comment]
you need to uplift ipam in `config/ipam/kustomization.yaml` too.

**Review by adilGhaffarDev — APPROVED** [review]
/lgtm

**Review by lentzi90 — COMMENTED** [review]
/approve

**Pull request merged**
