### PR TITLE
🌱 Add Adil as reviewer

### PR DESCRIPTION
**Pull request by lentzi90**
**What this PR does / why we need it**:

This adds @adilGhaffarDev as reviewer! :tada: 
Adil has done a great job with live-iso testing and redfish-virtualmedia among others.

### CODE REVIEW

**Comment by mboukhalfa** [comment]
/lgtm 
Thanks for the contributions @adilGhaffarDev

**Comment by kashifest** [comment]
/approve
Well done @adilGhaffarDev

**Pull request merged**
