### PR TITLE
🌱 Update README on job triggers in release-1.7

### PR DESCRIPTION
**Pull request by mboukhalfa**
This PR:
Update build status badges
Update compatibility table
Update test triggers

### CODE REVIEW

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Review by kashifest — COMMENTED** [review]
/approve

**Comment by tuminoid** [comment]
/retitle 🌱 Update README on job triggers in release-1.7
to workaround tide

**Comment by tuminoid** [comment]
markdownlint failed after project-infra PR got merged and actually works now. Please fix.

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Pull request merged**
