### PR TITLE
🐛 Fix pivoting based e2e test file name

### PR DESCRIPTION
**Pull request by slintes**
**What this PR does / why we need it**:

Renaming `pivoting_based_feature_tests.go` because at least Goland complains about a non test file (`*tests.go`, note the trailing `s `) using a private function (e.g. `validateGlobals()`)  of a test file (`e2e_suite_test.go`).

Introduced by #572 

/cc @mboukhalfa @furkatgofurov7 @smoshiur1237

### CODE REVIEW

**Review by furkatgofurov7 — APPROVED** [review]
Thanks, looks like we overlooked the file name.

/retitle 🐛 Fix pivoting based e2e test file name
/approve

**Comment by mboukhalfa** [comment]
/lgtm
Thanks for the fix

**Pull request merged**
