### PR TITLE
wip: 🐛 Fix for v1.6 clusterctl upgrade.

### PR DESCRIPTION
**Pull request by adilGhaffarDev**
**What this PR does / why we need it**:
Fix CI for v1.6 clusterctl upgrade.

### CODE REVIEW

**Comment by adilGhaffarDev** [comment]
/test_from-release-1-6_main_e2e_clusterctl_upgrade_test_ubuntu

**Comment by kashifest** [comment]
> /test_from-release-1-6_main_e2e_clusterctl_upgrade_test_ubuntu

Lets find the correct phony and test if this works first

**Comment by adilGhaffarDev** [comment]
@kashifest for me triggers are not working can you try?

**Comment by tuminoid** [comment]
/test-e2e-upgrade-main-from-release-1.6

**Comment by kashifest** [comment]
/test-e2e-upgrade-main-release-1.6

**Comment by tuminoid** [comment]
/test-e2e-upgrade-main-1.6

Nice guessing game, even if we have it documented? :)

**Comment by tuminoid** [comment]
/test-e2e-upgrade-main-from-release-1.6

**Comment by kashifest** [comment]
/test-e2e-upgrade-main-v1.6

**Comment by tuminoid** [comment]
> /test-e2e-upgrade-main-from-release-1-6

This is the correct keyword btw. It just seems Jenkins is not cooperating, being slow and unresponsive at the time.

**Pull request closed without merging**
