### PR TITLE
🌱 schedule dependabot on certain day, and add ok-to-test automatically

### PR DESCRIPTION
**Pull request by tuminoid**
CAPM3 schedule:
- GH actions: tuesday
- Gomod: wednesday

Automatically add labels:
- ok-to-test

We have dynamic Prow scheduling now and proper requests, we should not suffer from load failures in very basic tests anymore.

### CODE REVIEW

**Comment by tuminoid** [comment]
/cc @kashifest
/hold

I want Kashif's opinion on this and other scheduling PRs, hence hold.

**Comment by tuminoid** [comment]
/unhold
/override metal3-centos-e2e-integration-test-main metal3-ubuntu-e2e-integration-test-main

**Review by Sunnatillo — COMMENTED** [review]
/lgtm

**Pull request merged**
