### PR TITLE
🌱 Bump cert-manager to v1.11.1

### LINKED ISSUE #928: Bump cert-manager to v0.11.1 in Tiltfile and scripts
**Detailed Description**

cert-manager version in the provider is pretty old and we need to update it. New cert manager version is available (https://github.com/cert-manager/cert-manager/releases) so let's use it.

**Anything else you would like to add:**

CAPI already uses newest cert-manager version (v0.11.1) in [main](https://github.com/kubernetes-sigs/cluster-api/pull/8529)/[release-1.4](https://github.com/kubernetes-sigs/cluster-api/pull/8532)/[release-1.3](https://github.com/kubernetes-sigs/cluster-api/pull/8533) branches so once merged we can also back-port it to relevant provider release branches.

/kind feature

### PR DESCRIPTION
**Pull request by zhouhao3**
Follows: https://github.com/kubernetes-sigs/cluster-api/pull/8533
Fixes #928

### CODE REVIEW

**Review by kashifest — APPROVED** [review]

**Comment by furkatgofurov7** [comment]
To make sure e2e tests will not be broken

/test-ubuntu-e2e-feature-main

**Review by furkatgofurov7 — COMMENTED** [review]
Thanks @zhouhao3!

/retitle 🌱 Bump cert-manager to v1.11.1
/lgtm

**Pull request merged**
