### PR TITLE
WIP 🌱 e2e remediation test

### PR DESCRIPTION
**Pull request by wgslr**
Reimplements the [remediation feature test](https://github.com/metal3-io/metal3-dev-env/blob/master/vm-setup/roles/v1aX_integration_test/tasks/remediation.yml) using the e2e test framework.

### CODE REVIEW

**Comment by wgslr** [comment]
I have rebased this PR on top of #232, since I assume 232 will be merged before this PR is ready. Otherwise, grab the few newest commits and rebase them onto master.

**Comment by namnx228** [comment]
/close Open the new Pr for the same commits without the WIP status. 
https://github.com/metal3-io/cluster-api-provider-metal3/pull/294

**Comment by fmuyassarov** [comment]
We could just remove the WIP here. But okay
/close

**Pull request closed without merging**
