### PR TITLE
🌱Add more shortNames for metal3 config objects

### PR DESCRIPTION
**Pull request by Insullone**
Add more shortNames for metal3 config objects in a consistent way.

### CODE REVIEW

**Comment by fmuyassarov** [comment]
Seems we have some flakiness on the golint, because this is not the first PR that I'm seeing issue with golint.

**Comment by furkatgofurov7** [comment]
> Seems we have some flakiness on the golint, because this is not the first PR that I'm seeing issue with golint.

I am working on it, will update it.

**Comment by furkatgofurov7** [comment]
> I am working on it, will update it.

potential fix: #176

**Review by furkatgofurov7 — COMMENTED** [review]
/lgtm

**Pull request merged**
