### PR TITLE
:bug: Clusterclass e2e test fix

### PR DESCRIPTION
**Pull request by p-strusiewiczsurmacki-mobica**
This PR is a followup to #1405

It fixes issues with redundant test env related vars and configs that couses the test to fail at start. Those were removed in #1624 and should be also removed for clusterclass.

Also, it tries to fix issue with `{{ ds.meta_data.hostname }}'` reference reported [in the comment here](https://github.com/metal3-io/cluster-api-provider-metal3/pull/1405#discussion_r1584187652).

It seems that,[ according to the cluster-api repository](https://github.com/kubernetes-sigs/cluster-api/blob/main/bootstrap/kubeadm/api/v1beta1/kubeadm_types.go#L231), `NodeRegistration.Name` defaults to hostname, so I believe referencing hostname explicitly here is redundant and minght be deleted.

### CODE REVIEW

**Comment by kashifest** [comment]
/approve
Thanks a lot for the fix @p-strusiewiczsurmacki-mobica

**Comment by tuminoid** [comment]
The link to the centos e2e points to completely different PR.

Anyways, ubuntu passed, 
/override metal3-centos-e2e-integration-test-main

**Pull request merged**
