### PR TITLE
:seedling: Uplift BMO to v0.8.0 and IPAM to v1.8.0

### PR DESCRIPTION
**Pull request by mquhuy**
This PR uplifts BMO to v0.8.0 and IPAM to v1.8.0

### CODE REVIEW

**Review by tuminoid — COMMENTED** [review]
/approve

**Review by kashifest — COMMENTED** [review]
/lgtm

**Review by Rozzii — COMMENTED** [review]
/lgtm

**Comment by tuminoid** [comment]
/lgtm
re-add lgtm

**Pull request merged**
