### PR TITLE
🌱 Add release markers to e2e config

### PR DESCRIPTION
**Pull request by adilGhaffarDev**
**What this PR does / why we need it**:
Adding release markers in e2e config and clusterctl upgrade tests. These markers resolve to the latest patch release of the minor mentioned in the marker.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by kashifest — COMMENTED** [review]
/approve

**Review by Sunnatillo — APPROVED** [review]
/lgtm

**Pull request merged**
