### PR TITLE
✨ Automate releasing process with GitHub actions

### PR DESCRIPTION
**Pull request by fmuyassarov**
**What this PR does / why we need it**:
This automates releasing process via GitHub actions. 
Whenever there is a new tag pushed to the repository,
GitHub actions will execute `release.yaml`, which will
run `make release-notes`, `make release-manifests`
and and publish all the generated artifacts.

### CODE REVIEW

**Review by kashifest — APPROVED** [review]

**Review by furkatgofurov7 — COMMENTED** [review]
/lgtm

**Pull request merged**
