### PR TITLE
🌱 Update e2e integration triggers

### PR DESCRIPTION
**Pull request by mboukhalfa**
Updating readme after migrating e2e integration to prow jenkins operator

### CODE REVIEW

**Comment by tuminoid** [comment]
Should the GH side required tests be updated for CAPM3 main now?

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Review by kashifest — COMMENTED** [review]
/approve

**Comment by kashifest** [comment]
> Should the GH side required tests be updated for CAPM3 now?

Yes I think

**Comment by tuminoid** [comment]
OK, let's then run them here, so they appear as valid choices.

/test ?

**Comment by tuminoid** [comment]
/test metal3-centos-e2e-integration-test-main

I don't see anything matching `test-ubuntu-integration-main` ?

**Comment by tuminoid** [comment]
Also, we need a Prow job to update required tests in project-infra.

/hold

**Comment by mboukhalfa** [comment]
> /test metal3-centos-e2e-integration-test-main
> 
> I don't see anything matching `test-ubuntu-integration-main` ?

there is :  metal3-ubuntu-e2e-integration-test-main

**Comment by mboukhalfa** [comment]
PR to make prow required https://github.com/metal3-io/project-infra/pull/698

**Review by Sunnatillo — COMMENTED** [review]
/lgtm

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Pull request merged**
