### PR TITLE
Fix the flaky issue with cert-rotation

### PR DESCRIPTION
**Pull request by namnx228**
This PR is a back-port of https://github.com/metal3-io/cluster-api-provider-metal3/pull/407

### CODE REVIEW

**Review by mboukhalfa — APPROVED** [review]

**Review by Rozzii — APPROVED** [review]

**Review by furkatgofurov7 — APPROVED** [review]
/approve

**Comment by furkatgofurov7** [comment]
cc @fmuyassarov @smoshiur1237

**Review by furkatgofurov7 — COMMENTED** [review]
Since this is just a backport and actual PR already landed in main branch, merging it.

/lgtm

**Pull request merged**
