### PR TITLE
🌱 Uplift CAPI version for fakeapi

### PR DESCRIPTION
**Pull request by Sunnatillo**
Uplifts CAPI version for fakeapi. 
We forgot to update it on [this PR](https://github.com/metal3-io/cluster-api-provider-metal3/pull/2075) as fakeapi server added recently.

### CODE REVIEW

**Comment by Sunnatillo** [comment]
/override metal3-centos-e2e-integration-test-main metal3-ubuntu-e2e-integration-test-main 
Running tests does not check the changes. 

Do we have fake api test triggers?

**Comment by tuminoid** [comment]
> Do we have fake api test triggers?

I don't think we yet have any.

**Review by tuminoid — COMMENTED** [review]
/approve

**Pull request merged**
