### PR TITLE
🌱Uplift capi to v1.2

### PR DESCRIPTION
**Pull request by adilGhaffarDev**
Follwing go modules uplifted
- sigs.k8s.io/controller-runtime: v0.11.x => v0.12.3
- sigs.k8s.io/controller-tools: v0.8.x => v0.9.1
- sigs.k8s.io/kind: v0.11.x => v0.14.0
- k8s.io/*: v0.23.5 => v0.24.3 (derived from controller-runtime)
- github.com/onsi/gomega: v0.17.0 => v0.18.1 (derived from controller-runtime)
- k8s.io/kubectl: v0.23.5 => 0.24.0

### CODE REVIEW

**Comment by furkatgofurov7** [comment]
I suggest testing this, https://github.com/metal3-io/ip-address-manager/pull/125 and https://github.com/metal3-io/baremetal-operator/pull/1149 all together from the metal3-dev-env test PR.

**Comment by adilGhaffarDev** [comment]
metal3-dev-env test PR: https://github.com/metal3-io/metal3-dev-env/pull/1050

**Comment by adilGhaffarDev** [comment]
Testing with metal3-dev-env(https://github.com/metal3-io/metal3-dev-env/pull/1050) passed. Test reults:

- https://jenkins.nordix.org/job/metal3_capm3_main_e2e_test_centos/49/
- https://jenkins.nordix.org/job/metal3_capm3_main_e2e_test_ubuntu/36/
- https://jenkins.nordix.org/job/metal3_capm3_main_integration_test_ubuntu/24/

**Review by lentzi90 — APPROVED** [review]

**Comment by fmuyassarov** [comment]
/approve
/lgtm
Merging it manually since test will not pass until we merge it and https://github.com/metal3-io/baremetal-operator/pull/1149, https://github.com/metal3-io/ip-address-manager/pull/125

**Pull request merged**
