### PR TITLE
:seedling: Replace ironic image tag with main

### PR DESCRIPTION
**Pull request by kashifest**
Ironic image default tag has been updated to main.

### CODE REVIEW

**Review by mboukhalfa — APPROVED** [review]

**Review by furkatgofurov7 — APPROVED** [review]

**Review by Rozzii — APPROVED** [review]

**Review by fmuyassarov — COMMENTED** [review]
/lgtm

**Comment by fmuyassarov** [comment]
/retitle :seedling: Replace ironic image tag with main

**Pull request merged**
