### PR TITLE
📖 Update trigger phrases with new changes in CI

### PR DESCRIPTION
**Pull request by furkatgofurov7**
**What this PR does / why we need it**:

Related to:
https://github.com/metal3-io/project-infra/pull/415
https://gerrit.nordix.org/c/infra/cicd/+/14151

Edit: Also updates ref links to daily jobs in root README file

### CODE REVIEW

**Comment by furkatgofurov7** [comment]
This is for testing only:
/test-centos-integration-main
/test-centos-integration-release-0-5

**Comment by furkatgofurov7** [comment]
This is for testing only too:
/test-ubuntu-e2e-main
/test-centos-e2e-main
/test-ubuntu-e2e-parallel-main
/test-centos-e2e-parallel-main

**Review by lentzi90 — APPROVED** [review]

**Review by kashifest — APPROVED** [review]

**Pull request merged**
