### PR TITLE
🌱 Updating clusterctl tests for release 1.8

### PR DESCRIPTION
**Pull request by adilGhaffarDev**
**What this PR does / why we need it**:
Updating clusterctl tests for release 1.8

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Part of https://github.com/metal3-io/cluster-api-provider-metal3/issues/1887

### CODE REVIEW

**Review by tuminoid — COMMENTED** [review]
/approve

**Review by lentzi90 — COMMENTED** [review]
/lgtm
Should we get rid of v1.5 tests also?

**Review by smoshiur1237 — COMMENTED** [review]
/lgtm

**Comment by adilGhaffarDev** [comment]
> Should we get rid of v1.5 tests also?

Yes, I think we have removed them. Where do you see them? are you talking about e2e-config file?

**Comment by lentzi90** [comment]
Yes I see it in the e2e-config here: https://github.com/metal3-io/cluster-api-provider-metal3/blob/fd5098e068775784d61269f6eaf3c8893b46a2c7/test/e2e/config/e2e_conf.yaml#L47

**Comment by adilGhaffarDev** [comment]
> Yes I see it in the e2e-config here:

Yes I will remove them they are not in use anymore

**Pull request merged**
