### PR TITLE
🐛 Increase timeout pod restart in e2e test

### PR DESCRIPTION
**Pull request by namnx228**
This PR fixes this issue:
```
Timed out after 240.000s.
    Expected
        <*errors.errorString | 0xc000504ac0>: {
            s: "ironic-conductor is not restarted",
        }
    to be nil
```
The approach is to increase the timeout, so the ironic-conductor has time to restart.

### CODE REVIEW

**Comment by namnx228** [comment]
Pass the 1st time. Keep testing
/test-v1a5-centos-e2e

**Comment by namnx228** [comment]
Pass the 2nd time. Keep testing
/test-v1a5-centos-e2e

**Comment by mboukhalfa** [comment]
@namnx228 Increasing the timeout is included in the PR #345 I think we can close this PR ?

**Comment by namnx228** [comment]
@mboukhalfa Yes, let close this PR after #345 is merged

**Comment by furkatgofurov7** [comment]
@namnx228 do we still need this PR?

**Comment by namnx228** [comment]
@furkatgofurov7 no, we don't. We can close it.
/close

**Pull request closed without merging**
