### PR TITLE
🌱 Bump k8s version to v1.28.1

### PR DESCRIPTION
**Pull request by kashifest**
This PR also bumps the init cluster k8s version to v1.27.4 for feature test.

### CODE REVIEW

**Comment by kashifest** [comment]
/hold
Until https://github.com/Nordix/metal3-dev-tools/pull/691 is merged and images are available in artifactory.

**Review by lentzi90 — COMMENTED** [review]
/approve

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Review by Sunnatillo — APPROVED** [review]
LGTM

**Pull request merged**
