### PR TITLE
:seedling: Backport support for dev-env new network variable names in e2e tests (release-1.2)

### PR DESCRIPTION
**Pull request by Rozzii**
A number of different networking related variables have been renamed in metal3-dev-env and the changes will be tested with capm3 e2e integration tests thus capm3 have to support both the old and the new variable names during the transitioning period.

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
/lgtm

I would suggest relabeling as seedling since it only has to do with test code/variables

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Pull request merged**
