### PR TITLE
WIP: 🌱 Bump CAPI  to v1.8.0-beta.0

### LINKED ISSUE #1844: CAPI v1.8.0-beta.0 has been released and is ready for testing
CAPI v1.8.0-beta.0 has been released and is ready for testing.
Looking forward to your feedback before v1.8.0 release!

## For quick reference

- [CAPI v1.8.0-beta.0 release notes](https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.8.0-beta.0)
- [Shortcut to CAPI git issues](https://github.com/kubernetes-sigs/cluster-api/issues)

## Following are the planned dates for the upcoming releases

CAPI v1.8.0 will be released on **Monday, 12th August 2024**.

More details of the upcoming schedule can be seen at [CAPI v1.8.0 release timeline](https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/releases/release-1.8.md#timeline).

### PR DESCRIPTION
**Pull request by Sunnatillo**
Uplifts CAPI  to v1.8.0-beta.0

ClusterProxy.Apply() function is replaced ClusterProxy.CreateOrUpdate(), later does not accept namespace as an argument. 
 
Fixes #1844

### CODE REVIEW

**Comment by Sunnatillo** [comment]
we need a proper fix

**Comment by adilGhaffarDev** [comment]
> we need a proper fix

I can take a look, seems like there are some changes in CAPI e2e framework.

**Comment by Sunnatillo** [comment]
/test metal3-e2e-clusterctl-upgrade-test-main 
PR has related changes

**Comment by adilGhaffarDev** [comment]
@Sunnatillo please change the title and description too to beta1 from beta0.

**Comment by Sunnatillo** [comment]
/close
Superseeded by #1859

**Pull request closed without merging**
