### PR TITLE
🌱 add dependabot config for release-1.8

### PR DESCRIPTION
**Pull request by tuminoid**
Add dependabot config for release-1.8.

### CODE REVIEW

**Comment by tuminoid** [comment]
/override metal3-centos-e2e-integration-test-main metal3-ubuntu-e2e-integration-test-main

**Review by kashifest — COMMENTED** [review]
/approve

**Comment by tuminoid** [comment]
/hold
Fixing them.

**Comment by tuminoid** [comment]
/override metal3-centos-e2e-integration-test-main metal3-ubuntu-e2e-integration-test-main

**Review by smoshiur1237 — COMMENTED** [review]
/approve

**Review by Rozzii — COMMENTED** [review]
/lgtm

**Pull request merged**
