### PR TITLE
🌱 Remove duplicate healthcheck test trigger file

### PR DESCRIPTION
**Pull request by mboukhalfa**
healthcheck test is called from `remediation_based_feature_test.go` the file `healthcheck_test.go` is not needed

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
Makes sense
/approve

**Review by smoshiur1237 — APPROVED** [review]
/lgtm

**Comment by tuminoid** [comment]
/override keep-test-ubuntu-e2e-feature-main 
Non required keep test.

**Pull request merged**
