### PR TITLE
🌱 Bump docker go module to v26.0.0

### PR DESCRIPTION
**Pull request by kashifest**
as the title says

### CODE REVIEW

**Comment by kashifest** [comment]
This should close the failed dependabot attempt https://github.com/metal3-io/cluster-api-provider-metal3/pull/1557

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Review by smoshiur1237 — COMMENTED** [review]
/lgtm

**Review by furkatgofurov7 — APPROVED** [review]

**Pull request merged**
