### PR TITLE
🌱 Uplift golangci-lint in hack/tools/go.mod

### PR DESCRIPTION
**Pull request by furkatgofurov7**
**What this PR does / why we need it**:
Also uplift kustomize to [`v4.3.0`](https://pkg.go.dev/sigs.k8s.io/kustomize/kustomize/v4)

Upd: keeping in sync with [CAPI](https://github.com/kubernetes-sigs/cluster-api/pull/5166/files)

### CODE REVIEW

**Review by kashifest — APPROVED** [review]

**Comment by furkatgofurov7** [comment]
cc @jan-est @namnx228

**Pull request merged**
