### PR TITLE
🌱Remove static calico files from E2E tests

### PR DESCRIPTION
**Pull request by furkatgofurov7**
**What this PR does / why we need it**:
In e2e tests, currently, we fetch calico manifests on the fly and make corresponding changes to the manifest based on the OS, thus making static calico manifests redundant. This PR removes those static files and tweaks e2e suite tests accordingly.

### CODE REVIEW

**Comment by furkatgofurov7** [comment]
/retitle 🌱Remove static calico files from E2E tests
/test-v1b1-integration

**Review by kashifest — APPROVED** [review]

**Pull request merged**
