### PR TITLE
:seedling: Add unit tests for duplicateProviderIDsExist

### PR DESCRIPTION
**Pull request by peppi-lotta**
**What this PR does / why we need it**:
Add unit tests for method duplicateProviderIDsExist (metal3machine_manager.go). 
A problem was detected and fixed in https://github.com/metal3-io/cluster-api-provider-metal3/pull/675. These unit tests will prevent errors hopefully. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by Rozzii** [comment]
Add please a test where both provider IDs are empty string, and the node count is 1 , that should cause no duplication error.

**Comment by Rozzii** [comment]
This PR  only contains  unit test changes thus it has no effect on e2e feature or e2e integration tests.
/override metal3-centos-e2e-integration-test-main

**Review by kashifest — COMMENTED** [review]
/approve
Excellent work @peppi-lotta

**Pull request merged**
