### PR TITLE
🌱 Add zhouhao3 as a reviewer

### PR DESCRIPTION
**Pull request by zhouhao3**
To contribute further to the community, I would like to be a reviewer. Here is my contribution(10 min commits):
https://github.com/metal3-io/cluster-api-provider-metal3/pulls?q=is%3Apr+is%3Aclosed+author%3Azhouhao3

Signed-off-by: Zhou Hao <zhouhao@fujitsu.com>

### CODE REVIEW

**Comment by kashifest** [comment]
/approve
Thanks @zhouhao3

**Review by furkatgofurov7 — COMMENTED** [review]
/retitle 🌱 Add zhouhao3 as a reviewer
Thanks @zhouhao3 for all your contributions to CAPM3 so far :tada:
/lgtm

**Pull request merged**
