### PR TITLE
✨ Update master reference to main/controlplane and BMO reference to main branch

### PR DESCRIPTION
**Pull request by kashifest**

### CODE REVIEW

**Comment by namnx228** [comment]
/test-v1b1-e2e
/test-v1b1-centos-e2e
@furkatgofurov7 Do you think we need e2e v1a5 test on this PR?

**Comment by furkatgofurov7** [comment]
> @furkatgofurov7 Do you think we need e2e v1a5 test on this PR?

no, you should not run v1a5 e2e on the main branch, but only release-0.5. We have to cherry pick this one to release-0.5 once it is merged and trigger v1a5 e2e tests there.

**Review by furkatgofurov7 — APPROVED** [review]
/cc @namnx228

**Pull request merged**
