### PR TITLE
🌱 Uplift CAPI to v1.3.2 

### PR DESCRIPTION
**Pull request by furkatgofurov7**
**What this PR does / why we need it**:
https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.3.2

### CODE REVIEW

**Comment by kashifest** [comment]
Failure from upgrade test is interesting, I dont know if its broken in general 
```
Failed to run clusterctl config cluster
  Unexpected error:
      <*errors.withStack | 0xc0010fc7e0>: {
          error: <*errors.withMessage | 0xc0003f30e0>{
              cause: <*runtime.notRegisteredErr | 0xc000d2b320>{
                  schemeName: "pkg/runtime/scheme.go:100",
                  gvk: {
                      Group: "cluster.x-k8s.io",
                      Version: "v1alpha4",
                      Kind: "Cluster",
                  },
                  target: nil,
                  t: nil,
              },
              msg: "failed to convert object to Cluster",
          },
          stack: [0x1c62e4f, 0x1c62895, 0x1c64e65, 0x1c64773, 0x1c70b58, 0x1c7470f, 0x1d50d45, 0x1d52085, 0x861a3b, 0x874ad8, 0x4704c1],
      }
      failed to convert object to Cluster: no kind "Cluster" is registered for version "cluster.x-k8s.io/v1alpha4" in scheme "pkg/runtime/scheme.go:100"
```

/approve
/hold
Until all the tests pass.

**Comment by furkatgofurov7** [comment]
> Failure from upgrade test is interesting, I dont know if its broken in general
> 
> ```
> Failed to run clusterctl config cluster
>   Unexpected error:
>       <*errors.withStack | 0xc0010fc7e0>: {
>           error: <*errors.withMessage | 0xc0003f30e0>{
>               cause: <*runtime.notRegisteredErr | 0xc000d2b320>{
>                   schemeName: "pkg/runtime/scheme.go:100",
>                   gvk: {
>                       Group: "cluster.x-k8s.io",
>                       Version: "v1alpha4",
>                       Kind: "Cluster",
>                   },
>                   target: nil,
>                   t: nil,
>               },
>               msg: "failed to convert object to Cluster",
>           },
>           stack: [0x1c62e4f, 0x1c62895, 0x1c64e65, 0x1c64773, 0x1c70b58, 0x1c7470f, 0x1d50d45, 0x1d52085, 0x861a3b, 0x874ad8, 0x4704c1],
>       }
>       failed to convert object to Cluster: no kind "Cluster" is registered for version "cluster.x-k8s.io/v1alpha4" in scheme "pkg/runtime/scheme.go:100"
> ```
> 
> /approve /hold Until all the tests pass.

strange, this is just a go module update and not related to failure at all 🤔

**Pull request merged**
