### PR TITLE
✨Update generate example files according latest CAPI v1beta1

### PR DESCRIPTION
**Pull request by smoshiur1237**

### CODE REVIEW

**Comment by smoshiur1237** [comment]
Pass local depoly-example tests. 
/cc @furkatgofurov7 
/cc @fmuyassarov 
/cc @macaptain 
/cc @Xenwar

**Comment by fmuyassarov** [comment]
/lgtm

I hope there are not new mandatory fields in CAPI objects that we are missing. But probably not, since you have tested it.

**Review by furkatgofurov7 — APPROVED** [review]
/approve

**Pull request merged**
