### PR TITLE
🌱Add namespace directory in manifest collection

### PR DESCRIPTION
**Pull request by smoshiur1237**
There is a possibility to miss same kinds of manifest in different namespace. So this PR will add the namespace directory in manifest collection to gather all the manifests which will improve debugging capability.

### CODE REVIEW

**Comment by smoshiur1237** [comment]
One test would be enough to check the added directory, so overriding the 2nd test.
/override metal3-centos-e2e-integration-test-main

**Review by tuminoid — COMMENTED** [review]
/approve

**Review by mboukhalfa — APPROVED** [review]

**Comment by Rozzii** [comment]
Okay, i have got my answer offline, probably in the future we should improve on this in terms of not creating all the "kind" directories for all the namespaces because many of them will be just empty dirs but this PR is a step in the right direction.
/hold cancel
/lgtm

**Pull request merged**
