### PR TITLE
✨ e2e: prepare for the new ironic container

### PR DESCRIPTION
**Pull request by dtantsur**

### CODE REVIEW

**Comment by furkatgofurov7** [comment]
> Per your request

Thanks @dtantsur! Let's run e2e tests on this one. 

/test-v1b1-e2e

**Review by furkatgofurov7 — APPROVED** [review]
/approve

/cc @kashifest @lentzi90 @Xenwar

**Review by lentzi90 — APPROVED** [review]

**Review by elfosardo — APPROVED** [review]

**Review by smoshiur1237 — COMMENTED** [review]
/lgtm

**Pull request merged**
