### PR TITLE
🌱 Bump CAPI to v1.4.5 

### PR DESCRIPTION
**Pull request by kashifest**
Bump CAPI to v1.4.5 and update releasing doc to make sure we don't miss CAPI bumps before releasing. This PR also 
fixes deprecated use of docker containerStop function

### CODE REVIEW

**Review by tuminoid — COMMENTED** [review]
/lgtm 

Remember to make same documentation change to main.

**Comment by kashifest** [comment]
/hold
Seems some code change needs to be done after CAPI test module uplift

**Comment by tuminoid** [comment]
/hold 
Misclickety.

**Comment by tuminoid** [comment]
Something is funky with metal3-io bot/Prow and this PR. It keeps automatically re-running the tests every 10 minutes, and creates a lot of email spam via GH notifications. @kashifest @lentzi90

**Comment by tuminoid** [comment]
/ok-to-test 
/retest

Trying to break the cycle.

**Review by lentzi90 — COMMENTED** [review]
/approve

**Pull request merged**
